// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"

	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var TableNames = struct {
	Stocks              string
	UserCodes           string
	UserFavouriteStocks string
	Users               string
}{
	Stocks:              "stocks",
	UserCodes:           "user_codes",
	UserFavouriteStocks: "user_favourite_stocks",
	Users:               "users",
}

var ColumnNames = struct {
	Stocks              stockColumnNames
	UserCodes           userCodeColumnNames
	UserFavouriteStocks userFavouriteStockColumnNames
	Users               userColumnNames
}{
	Stocks: stockColumnNames{
		Symbol:        "symbol",
		CompanyNameVi: "company_name_vi",
		CompanyNameEn: "company_name_en",
		Exchange:      "exchange",
		Isin:          "isin",
		CreatedAt:     "created_at",
		UpdatedAt:     "updated_at",
	},
	UserCodes: userCodeColumnNames{
		ID:          "id",
		UserID:      "user_id",
		Value:       "value",
		Status:      "status",
		Type:        "type",
		ExpiredTime: "expired_time",
		UpdatedAt:   "updated_at",
		CreatedAt:   "created_at",
	},
	UserFavouriteStocks: userFavouriteStockColumnNames{
		ID:        "id",
		UserID:    "user_id",
		Symbol:    "symbol",
		Status:    "status",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
	},
	Users: userColumnNames{
		ID:        "id",
		FirstName: "first_name",
		LastName:  "last_name",
		Username:  "username",
		Password:  "password",
		Email:     "email",
		IsActive:  "is_active",
		UpdatedAt: "updated_at",
		CreatedAt: "created_at",
	},
}

var (
	SelectWhere = Where[*dialect.SelectQuery]()
	InsertWhere = Where[*dialect.InsertQuery]()
	UpdateWhere = Where[*dialect.UpdateQuery]()
	DeleteWhere = Where[*dialect.DeleteQuery]()
)

func Where[Q psql.Filterable]() struct {
	Stocks              stockWhere[Q]
	UserCodes           userCodeWhere[Q]
	UserFavouriteStocks userFavouriteStockWhere[Q]
	Users               userWhere[Q]
} {
	return struct {
		Stocks              stockWhere[Q]
		UserCodes           userCodeWhere[Q]
		UserFavouriteStocks userFavouriteStockWhere[Q]
		Users               userWhere[Q]
	}{
		Stocks:              StockWhere[Q](),
		UserCodes:           UserCodeWhere[Q](),
		UserFavouriteStocks: UserFavouriteStockWhere[Q](),
		Users:               UserWhere[Q](),
	}
}

var (
	SelectJoins = getJoins[*dialect.SelectQuery]
	UpdateJoins = getJoins[*dialect.UpdateQuery]
	DeleteJoins = getJoins[*dialect.DeleteQuery]
)

type joinSet[Q any] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

type joins[Q dialect.Joinable] struct {
	Stocks              joinSet[stockRelationshipJoins[Q]]
	UserCodes           joinSet[userCodeRelationshipJoins[Q]]
	UserFavouriteStocks joinSet[userFavouriteStockRelationshipJoins[Q]]
	Users               joinSet[userRelationshipJoins[Q]]
}

func getJoins[Q dialect.Joinable](ctx context.Context) joins[Q] {
	return joins[Q]{
		Stocks:              stocksJoin[Q](ctx),
		UserCodes:           userCodesJoin[Q](ctx),
		UserFavouriteStocks: userFavouriteStocksJoin[Q](ctx),
		Users:               usersJoin[Q](ctx),
	}
}
