// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"hash/maphash"

	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
)

var TableNames = struct {
	Chapters  string
	Stories   string
	UserCodes string
	Users     string
}{
	Chapters:  "chapters",
	Stories:   "stories",
	UserCodes: "user_codes",
	Users:     "users",
}

var ColumnNames = struct {
	Chapters  chapterColumnNames
	Stories   storyColumnNames
	UserCodes userCodeColumnNames
	Users     userColumnNames
}{
	Chapters: chapterColumnNames{
		ID:          "id",
		Name:        "name",
		StoryID:     "story_id",
		Status:      "status",
		Number:      "number",
		Description: "description",
		Content:     "content",
		CreatedBy:   "created_by",
		UpdatedAt:   "updated_at",
		CreatedAt:   "created_at",
		Metadata:    "metadata",
	},
	Stories: storyColumnNames{
		ID:          "id",
		Slug:        "slug",
		Name:        "name",
		Description: "description",
		Type:        "type",
		Status:      "status",
		ImageURL:    "image_url",
		CreatedBy:   "created_by",
		UpdatedAt:   "updated_at",
		CreatedAt:   "created_at",
	},
	UserCodes: userCodeColumnNames{
		ID:          "id",
		UserID:      "user_id",
		Value:       "value",
		Status:      "status",
		Type:        "type",
		ExpiredTime: "expired_time",
		UpdatedAt:   "updated_at",
		CreatedAt:   "created_at",
	},
	Users: userColumnNames{
		ID:        "id",
		FirstName: "first_name",
		LastName:  "last_name",
		Username:  "username",
		Password:  "password",
		Email:     "email",
		IsActive:  "is_active",
		UpdatedAt: "updated_at",
		CreatedAt: "created_at",
	},
}

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Chapters  chapterWhere[Q]
	Stories   storyWhere[Q]
	UserCodes userCodeWhere[Q]
	Users     userWhere[Q]
} {
	return struct {
		Chapters  chapterWhere[Q]
		Stories   storyWhere[Q]
		UserCodes userCodeWhere[Q]
		Users     userWhere[Q]
	}{
		Chapters:  buildChapterWhere[Q](ChapterColumns),
		Stories:   buildStoryWhere[Q](StoryColumns),
		UserCodes: buildUserCodeWhere[Q](UserCodeColumns),
		Users:     buildUserWhere[Q](UserColumns),
	}
}

var Preload = getPreloaders()

type preloaders struct {
	Chapter  chapterPreloader
	Story    storyPreloader
	UserCode userCodePreloader
	User     userPreloader
}

func getPreloaders() preloaders {
	return preloaders{
		Chapter:  buildChapterPreloader(),
		Story:    buildStoryPreloader(),
		UserCode: buildUserCodePreloader(),
		User:     buildUserPreloader(),
	}
}

var (
	SelectThenLoad = getThenLoaders[*dialect.SelectQuery]()
	InsertThenLoad = getThenLoaders[*dialect.InsertQuery]()
	UpdateThenLoad = getThenLoaders[*dialect.UpdateQuery]()
)

type thenLoaders[Q orm.Loadable] struct {
	Chapter  chapterThenLoader[Q]
	Story    storyThenLoader[Q]
	UserCode userCodeThenLoader[Q]
	User     userThenLoader[Q]
}

func getThenLoaders[Q orm.Loadable]() thenLoaders[Q] {
	return thenLoaders[Q]{
		Chapter:  buildChapterThenLoader[Q](),
		Story:    buildStoryThenLoader[Q](),
		UserCode: buildUserCodeThenLoader[Q](),
		User:     buildUserThenLoader[Q](),
	}
}

func thenLoadBuilder[Q orm.Loadable, T any](name string, f func(context.Context, bob.Executor, T, ...bob.Mod[*dialect.SelectQuery]) error) func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
	return func(queryMods ...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
		return orm.Loader[Q](func(ctx context.Context, exec bob.Executor, retrieved any) error {
			loader, isLoader := retrieved.(T)
			if !isLoader {
				return fmt.Errorf("object %T cannot load %q", retrieved, name)
			}

			err := f(ctx, exec, loader, queryMods...)

			// Don't cause an issue due to missing relationships
			if errors.Is(err, sql.ErrNoRows) {
				return nil
			}

			return err
		})
	}
}

var (
	SelectJoins = getJoins[*dialect.SelectQuery]()
	UpdateJoins = getJoins[*dialect.UpdateQuery]()
	DeleteJoins = getJoins[*dialect.DeleteQuery]()
)

type joinSet[Q interface{ aliasedAs(string) Q }] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

func (j joinSet[Q]) AliasedAs(alias string) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: j.InnerJoin.aliasedAs(alias),
		LeftJoin:  j.LeftJoin.aliasedAs(alias),
		RightJoin: j.RightJoin.aliasedAs(alias),
	}
}

type joins[Q dialect.Joinable] struct {
	Chapters  joinSet[chapterJoins[Q]]
	Stories   joinSet[storyJoins[Q]]
	UserCodes joinSet[userCodeJoins[Q]]
	Users     joinSet[userJoins[Q]]
}

func buildJoinSet[Q interface{ aliasedAs(string) Q }, C any, F func(C, string) Q](c C, f F) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: f(c, clause.InnerJoin),
		LeftJoin:  f(c, clause.LeftJoin),
		RightJoin: f(c, clause.RightJoin),
	}
}

func getJoins[Q dialect.Joinable]() joins[Q] {
	return joins[Q]{
		Chapters:  buildJoinSet[chapterJoins[Q]](ChapterColumns, buildChapterJoins),
		Stories:   buildJoinSet[storyJoins[Q]](StoryColumns, buildStoryJoins),
		UserCodes: buildJoinSet[userCodeJoins[Q]](UserCodeColumns, buildUserCodeJoins),
		Users:     buildJoinSet[userJoins[Q]](UserColumns, buildUserJoins),
	}
}

type modAs[Q any, C interface{ AliasedAs(string) C }] struct {
	c C
	f func(C) bob.Mod[Q]
}

func (m modAs[Q, C]) Apply(q Q) {
	m.f(m.c).Apply(q)
}

func (m modAs[Q, C]) AliasedAs(alias string) bob.Mod[Q] {
	m.c = m.c.AliasedAs(alias)
	return m
}

func randInt() int64 {
	out := int64(new(maphash.Hash).Sum64())

	if out < 0 {
		return -out % 10000
	}

	return out % 10000
}

// ErrUniqueConstraint captures all unique constraint errors by explicitly leaving `s` empty.
var ErrUniqueConstraint = &UniqueConstraintError{s: ""}

type UniqueConstraintError struct {
	// schema is the schema where the unique constraint is defined.
	schema string
	// table is the name of the table where the unique constraint is defined.
	table string
	// columns are the columns constituting the unique constraint.
	columns []string
	// s is a string uniquely identifying the constraint in the raw error message returned from the database.
	s string
}

func (e *UniqueConstraintError) Error() string {
	return e.s
}

func (e *UniqueConstraintError) Is(target error) bool {
	err, ok := target.(*pq.Error)
	if !ok {
		return false
	}
	return err.Code == "23505" && (e.s == "" || err.Constraint == e.s)
}
