// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Chapter is an object representing the database table.
type Chapter struct {
	ID          uuid.UUID                   `db:"id,pk" json:"id"`
	Name        string                      `db:"name" json:"name"`
	StoryID     uuid.UUID                   `db:"story_id" json:"story_id"`
	Status      string                      `db:"status" json:"status"`
	Number      int32                       `db:"number" json:"number"`
	Description sql.Null[string]            `db:"description" json:"description"`
	Content     sql.Null[string]            `db:"content" json:"content"`
	CreatedBy   sql.Null[uuid.UUID]         `db:"created_by" json:"created_by"`
	UpdatedAt   time.Time                   `db:"updated_at" json:"updated_at"`
	CreatedAt   time.Time                   `db:"created_at" json:"created_at"`
	Metadata    types.JSON[json.RawMessage] `db:"metadata" json:"metadata"`

	R chapterR `db:"-" json:"-"`
}

// ChapterSlice is an alias for a slice of pointers to Chapter.
// This should almost always be used instead of []*Chapter.
type ChapterSlice []*Chapter

// Chapters contains methods to work with the chapters table
var Chapters = psql.NewTablex[*Chapter, ChapterSlice, *ChapterSetter]("", "chapters")

// ChaptersQuery is a query on the chapters table
type ChaptersQuery = *psql.ViewQuery[*Chapter, ChapterSlice]

// chapterR is where relationships are stored.
type chapterR struct {
	CreatedByUser *User `json:"CreatedByUser"` // chapters.fk__chapters__users
}

type chapterColumnNames struct {
	ID          string
	Name        string
	StoryID     string
	Status      string
	Number      string
	Description string
	Content     string
	CreatedBy   string
	UpdatedAt   string
	CreatedAt   string
	Metadata    string
}

var ChapterColumns = buildChapterColumns("chapters")

type chapterColumns struct {
	tableAlias  string
	ID          psql.Expression
	Name        psql.Expression
	StoryID     psql.Expression
	Status      psql.Expression
	Number      psql.Expression
	Description psql.Expression
	Content     psql.Expression
	CreatedBy   psql.Expression
	UpdatedAt   psql.Expression
	CreatedAt   psql.Expression
	Metadata    psql.Expression
}

func (c chapterColumns) Alias() string {
	return c.tableAlias
}

func (chapterColumns) AliasedAs(alias string) chapterColumns {
	return buildChapterColumns(alias)
}

func buildChapterColumns(alias string) chapterColumns {
	return chapterColumns{
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Name:        psql.Quote(alias, "name"),
		StoryID:     psql.Quote(alias, "story_id"),
		Status:      psql.Quote(alias, "status"),
		Number:      psql.Quote(alias, "number"),
		Description: psql.Quote(alias, "description"),
		Content:     psql.Quote(alias, "content"),
		CreatedBy:   psql.Quote(alias, "created_by"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		Metadata:    psql.Quote(alias, "metadata"),
	}
}

type chapterWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	Name        psql.WhereMod[Q, string]
	StoryID     psql.WhereMod[Q, uuid.UUID]
	Status      psql.WhereMod[Q, string]
	Number      psql.WhereMod[Q, int32]
	Description psql.WhereNullMod[Q, string]
	Content     psql.WhereNullMod[Q, string]
	CreatedBy   psql.WhereNullMod[Q, uuid.UUID]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
	Metadata    psql.WhereMod[Q, types.JSON[json.RawMessage]]
}

func (chapterWhere[Q]) AliasedAs(alias string) chapterWhere[Q] {
	return buildChapterWhere[Q](buildChapterColumns(alias))
}

func buildChapterWhere[Q psql.Filterable](cols chapterColumns) chapterWhere[Q] {
	return chapterWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		Name:        psql.Where[Q, string](cols.Name),
		StoryID:     psql.Where[Q, uuid.UUID](cols.StoryID),
		Status:      psql.Where[Q, string](cols.Status),
		Number:      psql.Where[Q, int32](cols.Number),
		Description: psql.WhereNull[Q, string](cols.Description),
		Content:     psql.WhereNull[Q, string](cols.Content),
		CreatedBy:   psql.WhereNull[Q, uuid.UUID](cols.CreatedBy),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		Metadata:    psql.Where[Q, types.JSON[json.RawMessage]](cols.Metadata),
	}
}

var ChapterErrors = &chapterErrors{
	ErrUniqueChaptersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "chapters",
		columns: []string{"id"},
		s:       "chapters_pkey",
	},
}

type chapterErrors struct {
	ErrUniqueChaptersPkey *UniqueConstraintError
}

// ChapterSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ChapterSetter struct {
	ID          *uuid.UUID                   `db:"id,pk" json:"id"`
	Name        *string                      `db:"name" json:"name"`
	StoryID     *uuid.UUID                   `db:"story_id" json:"story_id"`
	Status      *string                      `db:"status" json:"status"`
	Number      *int32                       `db:"number" json:"number"`
	Description *sql.Null[string]            `db:"description" json:"description"`
	Content     *sql.Null[string]            `db:"content" json:"content"`
	CreatedBy   *sql.Null[uuid.UUID]         `db:"created_by" json:"created_by"`
	UpdatedAt   *time.Time                   `db:"updated_at" json:"updated_at"`
	CreatedAt   *time.Time                   `db:"created_at" json:"created_at"`
	Metadata    *types.JSON[json.RawMessage] `db:"metadata" json:"metadata"`
}

func (s ChapterSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID != nil {
		vals = append(vals, "id")
	}

	if s.Name != nil {
		vals = append(vals, "name")
	}

	if s.StoryID != nil {
		vals = append(vals, "story_id")
	}

	if s.Status != nil {
		vals = append(vals, "status")
	}

	if s.Number != nil {
		vals = append(vals, "number")
	}

	if s.Description != nil {
		vals = append(vals, "description")
	}

	if s.Content != nil {
		vals = append(vals, "content")
	}

	if s.CreatedBy != nil {
		vals = append(vals, "created_by")
	}

	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}

	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}

	if s.Metadata != nil {
		vals = append(vals, "metadata")
	}

	return vals
}

func (s ChapterSetter) Overwrite(t *Chapter) {
	if s.ID != nil {
		t.ID = *s.ID
	}
	if s.Name != nil {
		t.Name = *s.Name
	}
	if s.StoryID != nil {
		t.StoryID = *s.StoryID
	}
	if s.Status != nil {
		t.Status = *s.Status
	}
	if s.Number != nil {
		t.Number = *s.Number
	}
	if s.Description != nil {
		t.Description = *s.Description
	}
	if s.Content != nil {
		t.Content = *s.Content
	}
	if s.CreatedBy != nil {
		t.CreatedBy = *s.CreatedBy
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = *s.UpdatedAt
	}
	if s.CreatedAt != nil {
		t.CreatedAt = *s.CreatedAt
	}
	if s.Metadata != nil {
		t.Metadata = *s.Metadata
	}
}

func (s *ChapterSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Chapters.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 11)
		if s.ID != nil {
			vals[0] = psql.Arg(*s.ID)
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[1] = psql.Arg(*s.Name)
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.StoryID != nil {
			vals[2] = psql.Arg(*s.StoryID)
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Status != nil {
			vals[3] = psql.Arg(*s.Status)
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Number != nil {
			vals[4] = psql.Arg(*s.Number)
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Description != nil {
			vals[5] = psql.Arg(*s.Description)
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Content != nil {
			vals[6] = psql.Arg(*s.Content)
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedBy != nil {
			vals[7] = psql.Arg(*s.CreatedBy)
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[8] = psql.Arg(*s.UpdatedAt)
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[9] = psql.Arg(*s.CreatedAt)
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.Metadata != nil {
			vals[10] = psql.Arg(*s.Metadata)
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ChapterSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ChapterSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.StoryID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "story_id")...),
			psql.Arg(s.StoryID),
		}})
	}

	if s.Status != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.Number != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "number")...),
			psql.Arg(s.Number),
		}})
	}

	if s.Description != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.Content != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content")...),
			psql.Arg(s.Content),
		}})
	}

	if s.CreatedBy != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by")...),
			psql.Arg(s.CreatedBy),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.Metadata != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "metadata")...),
			psql.Arg(s.Metadata),
		}})
	}

	return exprs
}

// FindChapter retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindChapter(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Chapter, error) {
	if len(cols) == 0 {
		return Chapters.Query(
			SelectWhere.Chapters.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Chapters.Query(
		SelectWhere.Chapters.ID.EQ(IDPK),
		sm.Columns(Chapters.Columns().Only(cols...)),
	).One(ctx, exec)
}

// ChapterExists checks the presence of a single record by primary key
func ChapterExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Chapters.Query(
		SelectWhere.Chapters.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Chapter is retrieved from the database
func (o *Chapter) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Chapters.AfterSelectHooks.RunHooks(ctx, exec, ChapterSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Chapters.AfterInsertHooks.RunHooks(ctx, exec, ChapterSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Chapters.AfterUpdateHooks.RunHooks(ctx, exec, ChapterSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Chapters.AfterDeleteHooks.RunHooks(ctx, exec, ChapterSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Chapter
func (o *Chapter) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Chapter) pkEQ() dialect.Expression {
	return psql.Quote("chapters", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Chapter
func (o *Chapter) Update(ctx context.Context, exec bob.Executor, s *ChapterSetter) error {
	v, err := Chapters.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Chapter record with an executor
func (o *Chapter) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Chapters.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Chapter using the executor
func (o *Chapter) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Chapters.Query(
		SelectWhere.Chapters.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ChapterSlice is retrieved from the database
func (o ChapterSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Chapters.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Chapters.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Chapters.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Chapters.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ChapterSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("chapters", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ChapterSlice) copyMatchingRows(from ...*Chapter) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ChapterSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Chapters.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Chapter:
				o.copyMatchingRows(retrieved)
			case []*Chapter:
				o.copyMatchingRows(retrieved...)
			case ChapterSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Chapter or a slice of Chapter
				// then run the AfterUpdateHooks on the slice
				_, err = Chapters.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ChapterSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Chapters.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Chapter:
				o.copyMatchingRows(retrieved)
			case []*Chapter:
				o.copyMatchingRows(retrieved...)
			case ChapterSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Chapter or a slice of Chapter
				// then run the AfterDeleteHooks on the slice
				_, err = Chapters.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ChapterSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ChapterSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Chapters.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ChapterSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Chapters.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ChapterSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Chapters.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type chapterJoins[Q dialect.Joinable] struct {
	typ           string
	CreatedByUser modAs[Q, userColumns]
}

func (j chapterJoins[Q]) aliasedAs(alias string) chapterJoins[Q] {
	return buildChapterJoins[Q](buildChapterColumns(alias), j.typ)
}

func buildChapterJoins[Q dialect.Joinable](cols chapterColumns, typ string) chapterJoins[Q] {
	return chapterJoins[Q]{
		typ: typ,
		CreatedByUser: modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CreatedBy),
					))
				}

				return mods
			},
		},
	}
}

// CreatedByUser starts a query for related objects on users
func (o *Chapter) CreatedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.CreatedBy))),
	)...)
}

func (os ChapterSlice) CreatedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkCreatedBy := make(pgtypes.Array[sql.Null[uuid.UUID]], len(os))
	for i, o := range os {
		pkCreatedBy[i] = o.CreatedBy
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCreatedBy), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Chapter) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CreatedByUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("chapter cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByUser = rel

		if rel != nil {
			rel.R.CreatedByChapters = ChapterSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("chapter has no relationship %q", name)
	}
}

type chapterPreloader struct {
	CreatedByUser func(...psql.PreloadOption) psql.Preloader
}

func buildChapterPreloader() chapterPreloader {
	return chapterPreloader{
		CreatedByUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](orm.Relationship{
				Name: "CreatedByUser",
				Sides: []orm.RelSide{
					{
						From: TableNames.Chapters,
						To:   TableNames.Users,
						FromColumns: []string{
							ColumnNames.Chapters.CreatedBy,
						},
						ToColumns: []string{
							ColumnNames.Users.ID,
						},
					},
				},
			}, Users.Columns().Names(), opts...)
		},
	}
}

type chapterThenLoader[Q orm.Loadable] struct {
	CreatedByUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildChapterThenLoader[Q orm.Loadable]() chapterThenLoader[Q] {
	type CreatedByUserLoadInterface interface {
		LoadCreatedByUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return chapterThenLoader[Q]{
		CreatedByUser: thenLoadBuilder[Q](
			"CreatedByUser",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCreatedByUser loads the chapter's CreatedByUser into the .R struct
func (o *Chapter) LoadCreatedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByUser = nil

	related, err := o.CreatedByUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CreatedByChapters = ChapterSlice{o}

	o.R.CreatedByUser = related
	return nil
}

// LoadCreatedByUser loads the chapter's CreatedByUser into the .R struct
func (os ChapterSlice) LoadCreatedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.CreatedByUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.CreatedBy.V != rel.ID {
				continue
			}

			rel.R.CreatedByChapters = append(rel.R.CreatedByChapters, o)

			o.R.CreatedByUser = rel
			break
		}
	}

	return nil
}

func attachChapterCreatedByUser0(ctx context.Context, exec bob.Executor, count int, chapter0 *Chapter, user1 *User) (*Chapter, error) {
	setter := &ChapterSetter{
		CreatedBy: func() *sql.Null[uuid.UUID] {
			v := sql.Null[uuid.UUID]{V: user1.ID, Valid: true}
			return &v
		}(),
	}

	err := chapter0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachChapterCreatedByUser0: %w", err)
	}

	return chapter0, nil
}

func (chapter0 *Chapter) InsertCreatedByUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachChapterCreatedByUser0(ctx, exec, 1, chapter0, user1)
	if err != nil {
		return err
	}

	chapter0.R.CreatedByUser = user1

	user1.R.CreatedByChapters = append(user1.R.CreatedByChapters, chapter0)

	return nil
}

func (chapter0 *Chapter) AttachCreatedByUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachChapterCreatedByUser0(ctx, exec, 1, chapter0, user1)
	if err != nil {
		return err
	}

	chapter0.R.CreatedByUser = user1

	user1.R.CreatedByChapters = append(user1.R.CreatedByChapters, chapter0)

	return nil
}
