// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Stock is an object representing the database table.
type Stock struct {
	Symbol        string           `db:"symbol,pk" json:"symbol"`
	CompanyNameVi null.Val[string] `db:"company_name_vi" json:"company_name_vi"`
	CompanyNameEn null.Val[string] `db:"company_name_en" json:"company_name_en"`
	Exchange      null.Val[string] `db:"exchange" json:"exchange"`
	Isin          null.Val[string] `db:"isin" json:"isin"`
	CreatedAt     time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time        `db:"updated_at" json:"updated_at"`
}

// StockSlice is an alias for a slice of pointers to Stock.
// This should almost always be used instead of []*Stock.
type StockSlice []*Stock

// Stocks contains methods to work with the stocks table
var Stocks = psql.NewTablex[*Stock, StockSlice, *StockSetter]("", "stocks")

// StocksQuery is a query on the stocks table
type StocksQuery = *psql.ViewQuery[*Stock, StockSlice]

// StocksStmt is a prepared statment on stocks
type StocksStmt = bob.QueryStmt[*Stock, StockSlice]

// StockSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StockSetter struct {
	Symbol        omit.Val[string]     `db:"symbol,pk"`
	CompanyNameVi omitnull.Val[string] `db:"company_name_vi"`
	CompanyNameEn omitnull.Val[string] `db:"company_name_en"`
	Exchange      omitnull.Val[string] `db:"exchange"`
	Isin          omitnull.Val[string] `db:"isin"`
	CreatedAt     omit.Val[time.Time]  `db:"created_at"`
	UpdatedAt     omit.Val[time.Time]  `db:"updated_at"`
}

func (s StockSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if !s.Symbol.IsUnset() {
		vals = append(vals, "symbol")
	}

	if !s.CompanyNameVi.IsUnset() {
		vals = append(vals, "company_name_vi")
	}

	if !s.CompanyNameEn.IsUnset() {
		vals = append(vals, "company_name_en")
	}

	if !s.Exchange.IsUnset() {
		vals = append(vals, "exchange")
	}

	if !s.Isin.IsUnset() {
		vals = append(vals, "isin")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s StockSetter) Overwrite(t *Stock) {
	if !s.Symbol.IsUnset() {
		t.Symbol, _ = s.Symbol.Get()
	}
	if !s.CompanyNameVi.IsUnset() {
		t.CompanyNameVi, _ = s.CompanyNameVi.GetNull()
	}
	if !s.CompanyNameEn.IsUnset() {
		t.CompanyNameEn, _ = s.CompanyNameEn.GetNull()
	}
	if !s.Exchange.IsUnset() {
		t.Exchange, _ = s.Exchange.GetNull()
	}
	if !s.Isin.IsUnset() {
		t.Isin, _ = s.Isin.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s StockSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 7)
	if s.Symbol.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.Symbol)
	}

	if s.CompanyNameVi.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.CompanyNameVi)
	}

	if s.CompanyNameEn.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.CompanyNameEn)
	}

	if s.Exchange.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.Exchange)
	}

	if s.Isin.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.Isin)
	}

	if s.CreatedAt.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.CreatedAt)
	}

	if s.UpdatedAt.IsUnset() {
		vals[6] = psql.Raw("DEFAULT")
	} else {
		vals[6] = psql.Arg(s.UpdatedAt)
	}

	return im.Values(vals...)
}

func (s StockSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s StockSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if !s.Symbol.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "symbol")...),
			psql.Arg(s.Symbol),
		}})
	}

	if !s.CompanyNameVi.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "company_name_vi")...),
			psql.Arg(s.CompanyNameVi),
		}})
	}

	if !s.CompanyNameEn.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "company_name_en")...),
			psql.Arg(s.CompanyNameEn),
		}})
	}

	if !s.Exchange.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "exchange")...),
			psql.Arg(s.Exchange),
		}})
	}

	if !s.Isin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "isin")...),
			psql.Arg(s.Isin),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

type stockColumnNames struct {
	Symbol        string
	CompanyNameVi string
	CompanyNameEn string
	Exchange      string
	Isin          string
	CreatedAt     string
	UpdatedAt     string
}

var StockColumns = struct {
	Symbol        psql.Expression
	CompanyNameVi psql.Expression
	CompanyNameEn psql.Expression
	Exchange      psql.Expression
	Isin          psql.Expression
	CreatedAt     psql.Expression
	UpdatedAt     psql.Expression
}{
	Symbol:        psql.Quote("stocks", "symbol"),
	CompanyNameVi: psql.Quote("stocks", "company_name_vi"),
	CompanyNameEn: psql.Quote("stocks", "company_name_en"),
	Exchange:      psql.Quote("stocks", "exchange"),
	Isin:          psql.Quote("stocks", "isin"),
	CreatedAt:     psql.Quote("stocks", "created_at"),
	UpdatedAt:     psql.Quote("stocks", "updated_at"),
}

type stockWhere[Q psql.Filterable] struct {
	Symbol        psql.WhereMod[Q, string]
	CompanyNameVi psql.WhereNullMod[Q, string]
	CompanyNameEn psql.WhereNullMod[Q, string]
	Exchange      psql.WhereNullMod[Q, string]
	Isin          psql.WhereNullMod[Q, string]
	CreatedAt     psql.WhereMod[Q, time.Time]
	UpdatedAt     psql.WhereMod[Q, time.Time]
}

func StockWhere[Q psql.Filterable]() stockWhere[Q] {
	return stockWhere[Q]{
		Symbol:        psql.Where[Q, string](StockColumns.Symbol),
		CompanyNameVi: psql.WhereNull[Q, string](StockColumns.CompanyNameVi),
		CompanyNameEn: psql.WhereNull[Q, string](StockColumns.CompanyNameEn),
		Exchange:      psql.WhereNull[Q, string](StockColumns.Exchange),
		Isin:          psql.WhereNull[Q, string](StockColumns.Isin),
		CreatedAt:     psql.Where[Q, time.Time](StockColumns.CreatedAt),
		UpdatedAt:     psql.Where[Q, time.Time](StockColumns.UpdatedAt),
	}
}

// FindStock retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindStock(ctx context.Context, exec bob.Executor, SymbolPK string, cols ...string) (*Stock, error) {
	if len(cols) == 0 {
		return Stocks.Query(
			ctx, exec,
			SelectWhere.Stocks.Symbol.EQ(SymbolPK),
		).One()
	}

	return Stocks.Query(
		ctx, exec,
		SelectWhere.Stocks.Symbol.EQ(SymbolPK),
		sm.Columns(Stocks.Columns().Only(cols...)),
	).One()
}

// StockExists checks the presence of a single record by primary key
func StockExists(ctx context.Context, exec bob.Executor, SymbolPK string) (bool, error) {
	return Stocks.Query(
		ctx, exec,
		SelectWhere.Stocks.Symbol.EQ(SymbolPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the Stock
func (o *Stock) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.Symbol)
}

// Update uses an executor to update the Stock
func (o *Stock) Update(ctx context.Context, exec bob.Executor, s *StockSetter) error {
	return Stocks.Update(ctx, exec, s, o)
}

// Delete deletes a single Stock record with an executor
func (o *Stock) Delete(ctx context.Context, exec bob.Executor) error {
	return Stocks.Delete(ctx, exec, o)
}

// Reload refreshes the Stock using the executor
func (o *Stock) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Stocks.Query(
		ctx, exec,
		SelectWhere.Stocks.Symbol.EQ(o.Symbol),
	).One()
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

func (o StockSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StockSetter) error {
	return Stocks.Update(ctx, exec, &vals, o...)
}

func (o StockSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return Stocks.Delete(ctx, exec, o...)
}

func (o StockSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	SymbolPK := make([]string, len(o))

	for i, o := range o {
		SymbolPK[i] = o.Symbol
	}

	mods = append(mods,
		SelectWhere.Stocks.Symbol.In(SymbolPK...),
	)

	o2, err := Stocks.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.Symbol != old.Symbol {
				continue
			}

			*old = *new
			break
		}
	}

	return nil
}
