// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
)

// Stock is an object representing the database table.
type Stock struct {
	Symbol        string           `db:"symbol,pk" json:"symbol"`
	CompanyNameVi null.Val[string] `db:"company_name_vi" json:"company_name_vi"`
	CompanyNameEn null.Val[string] `db:"company_name_en" json:"company_name_en"`
	Exchange      null.Val[string] `db:"exchange" json:"exchange"`
	Isin          null.Val[string] `db:"isin" json:"isin"`
	CreatedAt     time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time        `db:"updated_at" json:"updated_at"`

	R stockR `db:"-" json:"-"`
}

// StockSlice is an alias for a slice of pointers to Stock.
// This should almost always be used instead of []*Stock.
type StockSlice []*Stock

// Stocks contains methods to work with the stocks table
var Stocks = psql.NewTablex[*Stock, StockSlice, *StockSetter]("", "stocks")

// StocksQuery is a query on the stocks table
type StocksQuery = *psql.ViewQuery[*Stock, StockSlice]

// StocksStmt is a prepared statment on stocks
type StocksStmt = bob.QueryStmt[*Stock, StockSlice]

// stockR is where relationships are stored.
type stockR struct {
	SymbolUserFavouriteStocks UserFavouriteStockSlice `json:"SymbolUserFavouriteStocks"` // user_favourite_stocks.fk_ufs_stock
	SymbolUserStockAlerts     UserStockAlertSlice     `json:"SymbolUserStockAlerts"`     // user_stock_alerts.fk_usa_stock
}

// StockSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StockSetter struct {
	Symbol        omit.Val[string]     `db:"symbol,pk"`
	CompanyNameVi omitnull.Val[string] `db:"company_name_vi"`
	CompanyNameEn omitnull.Val[string] `db:"company_name_en"`
	Exchange      omitnull.Val[string] `db:"exchange"`
	Isin          omitnull.Val[string] `db:"isin"`
	CreatedAt     omit.Val[time.Time]  `db:"created_at"`
	UpdatedAt     omit.Val[time.Time]  `db:"updated_at"`
}

func (s StockSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if !s.Symbol.IsUnset() {
		vals = append(vals, "symbol")
	}

	if !s.CompanyNameVi.IsUnset() {
		vals = append(vals, "company_name_vi")
	}

	if !s.CompanyNameEn.IsUnset() {
		vals = append(vals, "company_name_en")
	}

	if !s.Exchange.IsUnset() {
		vals = append(vals, "exchange")
	}

	if !s.Isin.IsUnset() {
		vals = append(vals, "isin")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s StockSetter) Overwrite(t *Stock) {
	if !s.Symbol.IsUnset() {
		t.Symbol, _ = s.Symbol.Get()
	}
	if !s.CompanyNameVi.IsUnset() {
		t.CompanyNameVi, _ = s.CompanyNameVi.GetNull()
	}
	if !s.CompanyNameEn.IsUnset() {
		t.CompanyNameEn, _ = s.CompanyNameEn.GetNull()
	}
	if !s.Exchange.IsUnset() {
		t.Exchange, _ = s.Exchange.GetNull()
	}
	if !s.Isin.IsUnset() {
		t.Isin, _ = s.Isin.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s StockSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 7)
	if s.Symbol.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.Symbol)
	}

	if s.CompanyNameVi.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.CompanyNameVi)
	}

	if s.CompanyNameEn.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.CompanyNameEn)
	}

	if s.Exchange.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.Exchange)
	}

	if s.Isin.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.Isin)
	}

	if s.CreatedAt.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.CreatedAt)
	}

	if s.UpdatedAt.IsUnset() {
		vals[6] = psql.Raw("DEFAULT")
	} else {
		vals[6] = psql.Arg(s.UpdatedAt)
	}

	return im.Values(vals...)
}

func (s StockSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s StockSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if !s.Symbol.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "symbol")...),
			psql.Arg(s.Symbol),
		}})
	}

	if !s.CompanyNameVi.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "company_name_vi")...),
			psql.Arg(s.CompanyNameVi),
		}})
	}

	if !s.CompanyNameEn.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "company_name_en")...),
			psql.Arg(s.CompanyNameEn),
		}})
	}

	if !s.Exchange.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "exchange")...),
			psql.Arg(s.Exchange),
		}})
	}

	if !s.Isin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "isin")...),
			psql.Arg(s.Isin),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

type stockColumnNames struct {
	Symbol        string
	CompanyNameVi string
	CompanyNameEn string
	Exchange      string
	Isin          string
	CreatedAt     string
	UpdatedAt     string
}

type stockRelationshipJoins[Q dialect.Joinable] struct {
	SymbolUserFavouriteStocks bob.Mod[Q]
	SymbolUserStockAlerts     bob.Mod[Q]
}

func buildStockRelationshipJoins[Q dialect.Joinable](ctx context.Context, typ string) stockRelationshipJoins[Q] {
	return stockRelationshipJoins[Q]{
		SymbolUserFavouriteStocks: stocksJoinSymbolUserFavouriteStocks[Q](ctx, typ),
		SymbolUserStockAlerts:     stocksJoinSymbolUserStockAlerts[Q](ctx, typ),
	}
}

func stocksJoin[Q dialect.Joinable](ctx context.Context) joinSet[stockRelationshipJoins[Q]] {
	return joinSet[stockRelationshipJoins[Q]]{
		InnerJoin: buildStockRelationshipJoins[Q](ctx, clause.InnerJoin),
		LeftJoin:  buildStockRelationshipJoins[Q](ctx, clause.LeftJoin),
		RightJoin: buildStockRelationshipJoins[Q](ctx, clause.RightJoin),
	}
}

var StockColumns = struct {
	Symbol        psql.Expression
	CompanyNameVi psql.Expression
	CompanyNameEn psql.Expression
	Exchange      psql.Expression
	Isin          psql.Expression
	CreatedAt     psql.Expression
	UpdatedAt     psql.Expression
}{
	Symbol:        psql.Quote("stocks", "symbol"),
	CompanyNameVi: psql.Quote("stocks", "company_name_vi"),
	CompanyNameEn: psql.Quote("stocks", "company_name_en"),
	Exchange:      psql.Quote("stocks", "exchange"),
	Isin:          psql.Quote("stocks", "isin"),
	CreatedAt:     psql.Quote("stocks", "created_at"),
	UpdatedAt:     psql.Quote("stocks", "updated_at"),
}

type stockWhere[Q psql.Filterable] struct {
	Symbol        psql.WhereMod[Q, string]
	CompanyNameVi psql.WhereNullMod[Q, string]
	CompanyNameEn psql.WhereNullMod[Q, string]
	Exchange      psql.WhereNullMod[Q, string]
	Isin          psql.WhereNullMod[Q, string]
	CreatedAt     psql.WhereMod[Q, time.Time]
	UpdatedAt     psql.WhereMod[Q, time.Time]
}

func StockWhere[Q psql.Filterable]() stockWhere[Q] {
	return stockWhere[Q]{
		Symbol:        psql.Where[Q, string](StockColumns.Symbol),
		CompanyNameVi: psql.WhereNull[Q, string](StockColumns.CompanyNameVi),
		CompanyNameEn: psql.WhereNull[Q, string](StockColumns.CompanyNameEn),
		Exchange:      psql.WhereNull[Q, string](StockColumns.Exchange),
		Isin:          psql.WhereNull[Q, string](StockColumns.Isin),
		CreatedAt:     psql.Where[Q, time.Time](StockColumns.CreatedAt),
		UpdatedAt:     psql.Where[Q, time.Time](StockColumns.UpdatedAt),
	}
}

// FindStock retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindStock(ctx context.Context, exec bob.Executor, SymbolPK string, cols ...string) (*Stock, error) {
	if len(cols) == 0 {
		return Stocks.Query(
			ctx, exec,
			SelectWhere.Stocks.Symbol.EQ(SymbolPK),
		).One()
	}

	return Stocks.Query(
		ctx, exec,
		SelectWhere.Stocks.Symbol.EQ(SymbolPK),
		sm.Columns(Stocks.Columns().Only(cols...)),
	).One()
}

// StockExists checks the presence of a single record by primary key
func StockExists(ctx context.Context, exec bob.Executor, SymbolPK string) (bool, error) {
	return Stocks.Query(
		ctx, exec,
		SelectWhere.Stocks.Symbol.EQ(SymbolPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the Stock
func (o *Stock) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.Symbol)
}

// Update uses an executor to update the Stock
func (o *Stock) Update(ctx context.Context, exec bob.Executor, s *StockSetter) error {
	return Stocks.Update(ctx, exec, s, o)
}

// Delete deletes a single Stock record with an executor
func (o *Stock) Delete(ctx context.Context, exec bob.Executor) error {
	return Stocks.Delete(ctx, exec, o)
}

// Reload refreshes the Stock using the executor
func (o *Stock) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Stocks.Query(
		ctx, exec,
		SelectWhere.Stocks.Symbol.EQ(o.Symbol),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o StockSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StockSetter) error {
	return Stocks.Update(ctx, exec, &vals, o...)
}

func (o StockSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return Stocks.Delete(ctx, exec, o...)
}

func (o StockSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	SymbolPK := make([]string, len(o))

	for i, o := range o {
		SymbolPK[i] = o.Symbol
	}

	mods = append(mods,
		SelectWhere.Stocks.Symbol.In(SymbolPK...),
	)

	o2, err := Stocks.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.Symbol != old.Symbol {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func stocksJoinSymbolUserFavouriteStocks[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, UserFavouriteStocks.NameAs(ctx)).On(
			UserFavouriteStockColumns.Symbol.EQ(StockColumns.Symbol),
		),
	}
}

func stocksJoinSymbolUserStockAlerts[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, UserStockAlerts.NameAs(ctx)).On(
			UserStockAlertColumns.Symbol.EQ(StockColumns.Symbol),
		),
	}
}

// SymbolUserFavouriteStocks starts a query for related objects on user_favourite_stocks
func (o *Stock) SymbolUserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserFavouriteStocksQuery {
	return UserFavouriteStocks.Query(ctx, exec, append(mods,
		sm.Where(UserFavouriteStockColumns.Symbol.EQ(psql.Arg(o.Symbol))),
	)...)
}

func (os StockSlice) SymbolUserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserFavouriteStocksQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.Symbol)
	}

	return UserFavouriteStocks.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserFavouriteStockColumns.Symbol).In(PKArgs...)),
	)...)
}

// SymbolUserStockAlerts starts a query for related objects on user_stock_alerts
func (o *Stock) SymbolUserStockAlerts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserStockAlertsQuery {
	return UserStockAlerts.Query(ctx, exec, append(mods,
		sm.Where(UserStockAlertColumns.Symbol.EQ(psql.Arg(o.Symbol))),
	)...)
}

func (os StockSlice) SymbolUserStockAlerts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserStockAlertsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.Symbol)
	}

	return UserStockAlerts.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserStockAlertColumns.Symbol).In(PKArgs...)),
	)...)
}

func (o *Stock) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "SymbolUserFavouriteStocks":
		rels, ok := retrieved.(UserFavouriteStockSlice)
		if !ok {
			return fmt.Errorf("stock cannot load %T as %q", retrieved, name)
		}

		o.R.SymbolUserFavouriteStocks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.SymbolStock = o
			}
		}
		return nil
	case "SymbolUserStockAlerts":
		rels, ok := retrieved.(UserStockAlertSlice)
		if !ok {
			return fmt.Errorf("stock cannot load %T as %q", retrieved, name)
		}

		o.R.SymbolUserStockAlerts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.SymbolStock = o
			}
		}
		return nil
	default:
		return fmt.Errorf("stock has no relationship %q", name)
	}
}

func ThenLoadStockSymbolUserFavouriteStocks(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadStockSymbolUserFavouriteStocks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load StockSymbolUserFavouriteStocks", retrieved)
		}

		err := loader.LoadStockSymbolUserFavouriteStocks(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadStockSymbolUserFavouriteStocks loads the stock's SymbolUserFavouriteStocks into the .R struct
func (o *Stock) LoadStockSymbolUserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SymbolUserFavouriteStocks = nil

	related, err := o.SymbolUserFavouriteStocks(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.SymbolStock = o
	}

	o.R.SymbolUserFavouriteStocks = related
	return nil
}

// LoadStockSymbolUserFavouriteStocks loads the stock's SymbolUserFavouriteStocks into the .R struct
func (os StockSlice) LoadStockSymbolUserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userFavouriteStocks, err := os.SymbolUserFavouriteStocks(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.SymbolUserFavouriteStocks = nil
	}

	for _, o := range os {
		for _, rel := range userFavouriteStocks {
			if o.Symbol != rel.Symbol {
				continue
			}

			rel.R.SymbolStock = o

			o.R.SymbolUserFavouriteStocks = append(o.R.SymbolUserFavouriteStocks, rel)
		}
	}

	return nil
}

func ThenLoadStockSymbolUserStockAlerts(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadStockSymbolUserStockAlerts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load StockSymbolUserStockAlerts", retrieved)
		}

		err := loader.LoadStockSymbolUserStockAlerts(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadStockSymbolUserStockAlerts loads the stock's SymbolUserStockAlerts into the .R struct
func (o *Stock) LoadStockSymbolUserStockAlerts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SymbolUserStockAlerts = nil

	related, err := o.SymbolUserStockAlerts(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.SymbolStock = o
	}

	o.R.SymbolUserStockAlerts = related
	return nil
}

// LoadStockSymbolUserStockAlerts loads the stock's SymbolUserStockAlerts into the .R struct
func (os StockSlice) LoadStockSymbolUserStockAlerts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userStockAlerts, err := os.SymbolUserStockAlerts(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.SymbolUserStockAlerts = nil
	}

	for _, o := range os {
		for _, rel := range userStockAlerts {
			if o.Symbol != rel.Symbol {
				continue
			}

			rel.R.SymbolStock = o

			o.R.SymbolUserStockAlerts = append(o.R.SymbolUserStockAlerts, rel)
		}
	}

	return nil
}

func insertStockSymbolUserFavouriteStocks0(ctx context.Context, exec bob.Executor, userFavouriteStocks1 []*UserFavouriteStockSetter, stock0 *Stock) (UserFavouriteStockSlice, error) {
	for i := range userFavouriteStocks1 {
		userFavouriteStocks1[i].Symbol = omit.From(stock0.Symbol)
	}

	ret, err := UserFavouriteStocks.InsertMany(ctx, exec, userFavouriteStocks1...)
	if err != nil {
		return ret, fmt.Errorf("insertStockSymbolUserFavouriteStocks0: %w", err)
	}

	return ret, nil
}

func attachStockSymbolUserFavouriteStocks0(ctx context.Context, exec bob.Executor, count int, userFavouriteStocks1 UserFavouriteStockSlice, stock0 *Stock) (UserFavouriteStockSlice, error) {
	setter := &UserFavouriteStockSetter{
		Symbol: omit.From(stock0.Symbol),
	}

	err := UserFavouriteStocks.Update(ctx, exec, setter, userFavouriteStocks1...)
	if err != nil {
		return nil, fmt.Errorf("attachStockSymbolUserFavouriteStocks0: %w", err)
	}

	return userFavouriteStocks1, nil
}

func (stock0 *Stock) InsertSymbolUserFavouriteStocks(ctx context.Context, exec bob.Executor, related ...*UserFavouriteStockSetter) error {
	if len(related) == 0 {
		return nil
	}

	userFavouriteStocks1, err := insertStockSymbolUserFavouriteStocks0(ctx, exec, related, stock0)
	if err != nil {
		return err
	}

	stock0.R.SymbolUserFavouriteStocks = append(stock0.R.SymbolUserFavouriteStocks, userFavouriteStocks1...)

	for _, rel := range userFavouriteStocks1 {
		rel.R.SymbolStock = stock0
	}
	return nil
}

func (stock0 *Stock) AttachSymbolUserFavouriteStocks(ctx context.Context, exec bob.Executor, related ...*UserFavouriteStock) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userFavouriteStocks1 := UserFavouriteStockSlice(related)

	_, err = attachStockSymbolUserFavouriteStocks0(ctx, exec, len(related), userFavouriteStocks1, stock0)
	if err != nil {
		return err
	}

	stock0.R.SymbolUserFavouriteStocks = append(stock0.R.SymbolUserFavouriteStocks, userFavouriteStocks1...)

	for _, rel := range related {
		rel.R.SymbolStock = stock0
	}

	return nil
}

func insertStockSymbolUserStockAlerts0(ctx context.Context, exec bob.Executor, userStockAlerts1 []*UserStockAlertSetter, stock0 *Stock) (UserStockAlertSlice, error) {
	for i := range userStockAlerts1 {
		userStockAlerts1[i].Symbol = omit.From(stock0.Symbol)
	}

	ret, err := UserStockAlerts.InsertMany(ctx, exec, userStockAlerts1...)
	if err != nil {
		return ret, fmt.Errorf("insertStockSymbolUserStockAlerts0: %w", err)
	}

	return ret, nil
}

func attachStockSymbolUserStockAlerts0(ctx context.Context, exec bob.Executor, count int, userStockAlerts1 UserStockAlertSlice, stock0 *Stock) (UserStockAlertSlice, error) {
	setter := &UserStockAlertSetter{
		Symbol: omit.From(stock0.Symbol),
	}

	err := UserStockAlerts.Update(ctx, exec, setter, userStockAlerts1...)
	if err != nil {
		return nil, fmt.Errorf("attachStockSymbolUserStockAlerts0: %w", err)
	}

	return userStockAlerts1, nil
}

func (stock0 *Stock) InsertSymbolUserStockAlerts(ctx context.Context, exec bob.Executor, related ...*UserStockAlertSetter) error {
	if len(related) == 0 {
		return nil
	}

	userStockAlerts1, err := insertStockSymbolUserStockAlerts0(ctx, exec, related, stock0)
	if err != nil {
		return err
	}

	stock0.R.SymbolUserStockAlerts = append(stock0.R.SymbolUserStockAlerts, userStockAlerts1...)

	for _, rel := range userStockAlerts1 {
		rel.R.SymbolStock = stock0
	}
	return nil
}

func (stock0 *Stock) AttachSymbolUserStockAlerts(ctx context.Context, exec bob.Executor, related ...*UserStockAlert) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userStockAlerts1 := UserStockAlertSlice(related)

	_, err = attachStockSymbolUserStockAlerts0(ctx, exec, len(related), userStockAlerts1, stock0)
	if err != nil {
		return err
	}

	stock0.R.SymbolUserStockAlerts = append(stock0.R.SymbolUserStockAlerts, userStockAlerts1...)

	for _, rel := range related {
		rel.R.SymbolStock = stock0
	}

	return nil
}
