// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Story is an object representing the database table.
type Story struct {
	ID          uuid.UUID           `db:"id,pk" json:"id"`
	Slug        string              `db:"slug" json:"slug"`
	Name        string              `db:"name" json:"name"`
	Description string              `db:"description" json:"description"`
	Type        string              `db:"type" json:"type"`
	Status      string              `db:"status" json:"status"`
	ImageURL    sql.Null[string]    `db:"image_url" json:"image_url"`
	CreatedBy   sql.Null[uuid.UUID] `db:"created_by" json:"created_by"`
	UpdatedAt   time.Time           `db:"updated_at" json:"updated_at"`
	CreatedAt   time.Time           `db:"created_at" json:"created_at"`

	R storyR `db:"-" json:"-"`
}

// StorySlice is an alias for a slice of pointers to Story.
// This should almost always be used instead of []*Story.
type StorySlice []*Story

// Stories contains methods to work with the stories table
var Stories = psql.NewTablex[*Story, StorySlice, *StorySetter]("", "stories")

// StoriesQuery is a query on the stories table
type StoriesQuery = *psql.ViewQuery[*Story, StorySlice]

// storyR is where relationships are stored.
type storyR struct {
	CreatedByUser *User `json:"CreatedByUser"` // stories.fk__stories__users
}

type storyColumnNames struct {
	ID          string
	Slug        string
	Name        string
	Description string
	Type        string
	Status      string
	ImageURL    string
	CreatedBy   string
	UpdatedAt   string
	CreatedAt   string
}

var StoryColumns = buildStoryColumns("stories")

type storyColumns struct {
	tableAlias  string
	ID          psql.Expression
	Slug        psql.Expression
	Name        psql.Expression
	Description psql.Expression
	Type        psql.Expression
	Status      psql.Expression
	ImageURL    psql.Expression
	CreatedBy   psql.Expression
	UpdatedAt   psql.Expression
	CreatedAt   psql.Expression
}

func (c storyColumns) Alias() string {
	return c.tableAlias
}

func (storyColumns) AliasedAs(alias string) storyColumns {
	return buildStoryColumns(alias)
}

func buildStoryColumns(alias string) storyColumns {
	return storyColumns{
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Slug:        psql.Quote(alias, "slug"),
		Name:        psql.Quote(alias, "name"),
		Description: psql.Quote(alias, "description"),
		Type:        psql.Quote(alias, "type"),
		Status:      psql.Quote(alias, "status"),
		ImageURL:    psql.Quote(alias, "image_url"),
		CreatedBy:   psql.Quote(alias, "created_by"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
		CreatedAt:   psql.Quote(alias, "created_at"),
	}
}

type storyWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	Slug        psql.WhereMod[Q, string]
	Name        psql.WhereMod[Q, string]
	Description psql.WhereMod[Q, string]
	Type        psql.WhereMod[Q, string]
	Status      psql.WhereMod[Q, string]
	ImageURL    psql.WhereNullMod[Q, string]
	CreatedBy   psql.WhereNullMod[Q, uuid.UUID]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
}

func (storyWhere[Q]) AliasedAs(alias string) storyWhere[Q] {
	return buildStoryWhere[Q](buildStoryColumns(alias))
}

func buildStoryWhere[Q psql.Filterable](cols storyColumns) storyWhere[Q] {
	return storyWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		Slug:        psql.Where[Q, string](cols.Slug),
		Name:        psql.Where[Q, string](cols.Name),
		Description: psql.Where[Q, string](cols.Description),
		Type:        psql.Where[Q, string](cols.Type),
		Status:      psql.Where[Q, string](cols.Status),
		ImageURL:    psql.WhereNull[Q, string](cols.ImageURL),
		CreatedBy:   psql.WhereNull[Q, uuid.UUID](cols.CreatedBy),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

var StoryErrors = &storyErrors{
	ErrUniqueStoriesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "stories",
		columns: []string{"id"},
		s:       "stories_pkey",
	},
}

type storyErrors struct {
	ErrUniqueStoriesPkey *UniqueConstraintError
}

// StorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StorySetter struct {
	ID          *uuid.UUID           `db:"id,pk" json:"id"`
	Slug        *string              `db:"slug" json:"slug"`
	Name        *string              `db:"name" json:"name"`
	Description *string              `db:"description" json:"description"`
	Type        *string              `db:"type" json:"type"`
	Status      *string              `db:"status" json:"status"`
	ImageURL    *sql.Null[string]    `db:"image_url" json:"image_url"`
	CreatedBy   *sql.Null[uuid.UUID] `db:"created_by" json:"created_by"`
	UpdatedAt   *time.Time           `db:"updated_at" json:"updated_at"`
	CreatedAt   *time.Time           `db:"created_at" json:"created_at"`
}

func (s StorySetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID != nil {
		vals = append(vals, "id")
	}

	if s.Slug != nil {
		vals = append(vals, "slug")
	}

	if s.Name != nil {
		vals = append(vals, "name")
	}

	if s.Description != nil {
		vals = append(vals, "description")
	}

	if s.Type != nil {
		vals = append(vals, "type")
	}

	if s.Status != nil {
		vals = append(vals, "status")
	}

	if s.ImageURL != nil {
		vals = append(vals, "image_url")
	}

	if s.CreatedBy != nil {
		vals = append(vals, "created_by")
	}

	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}

	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}

	return vals
}

func (s StorySetter) Overwrite(t *Story) {
	if s.ID != nil {
		t.ID = *s.ID
	}
	if s.Slug != nil {
		t.Slug = *s.Slug
	}
	if s.Name != nil {
		t.Name = *s.Name
	}
	if s.Description != nil {
		t.Description = *s.Description
	}
	if s.Type != nil {
		t.Type = *s.Type
	}
	if s.Status != nil {
		t.Status = *s.Status
	}
	if s.ImageURL != nil {
		t.ImageURL = *s.ImageURL
	}
	if s.CreatedBy != nil {
		t.CreatedBy = *s.CreatedBy
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = *s.UpdatedAt
	}
	if s.CreatedAt != nil {
		t.CreatedAt = *s.CreatedAt
	}
}

func (s *StorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Stories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID != nil {
			vals[0] = psql.Arg(*s.ID)
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Slug != nil {
			vals[1] = psql.Arg(*s.Slug)
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[2] = psql.Arg(*s.Name)
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Description != nil {
			vals[3] = psql.Arg(*s.Description)
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Type != nil {
			vals[4] = psql.Arg(*s.Type)
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Status != nil {
			vals[5] = psql.Arg(*s.Status)
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.ImageURL != nil {
			vals[6] = psql.Arg(*s.ImageURL)
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedBy != nil {
			vals[7] = psql.Arg(*s.CreatedBy)
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[8] = psql.Arg(*s.UpdatedAt)
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[9] = psql.Arg(*s.CreatedAt)
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s StorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s StorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Slug != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "slug")...),
			psql.Arg(s.Slug),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Description != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.Type != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.Status != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.ImageURL != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "image_url")...),
			psql.Arg(s.ImageURL),
		}})
	}

	if s.CreatedBy != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by")...),
			psql.Arg(s.CreatedBy),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindStory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindStory(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Story, error) {
	if len(cols) == 0 {
		return Stories.Query(
			SelectWhere.Stories.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Stories.Query(
		SelectWhere.Stories.ID.EQ(IDPK),
		sm.Columns(Stories.Columns().Only(cols...)),
	).One(ctx, exec)
}

// StoryExists checks the presence of a single record by primary key
func StoryExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Stories.Query(
		SelectWhere.Stories.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Story is retrieved from the database
func (o *Story) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Stories.AfterSelectHooks.RunHooks(ctx, exec, StorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Stories.AfterInsertHooks.RunHooks(ctx, exec, StorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Stories.AfterUpdateHooks.RunHooks(ctx, exec, StorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Stories.AfterDeleteHooks.RunHooks(ctx, exec, StorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Story
func (o *Story) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Story) pkEQ() dialect.Expression {
	return psql.Quote("stories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Story
func (o *Story) Update(ctx context.Context, exec bob.Executor, s *StorySetter) error {
	v, err := Stories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Story record with an executor
func (o *Story) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Stories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Story using the executor
func (o *Story) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Stories.Query(
		SelectWhere.Stories.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after StorySlice is retrieved from the database
func (o StorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Stories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Stories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Stories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Stories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o StorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("stories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o StorySlice) copyMatchingRows(from ...*Story) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o StorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Stories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Story:
				o.copyMatchingRows(retrieved)
			case []*Story:
				o.copyMatchingRows(retrieved...)
			case StorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Story or a slice of Story
				// then run the AfterUpdateHooks on the slice
				_, err = Stories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o StorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Stories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Story:
				o.copyMatchingRows(retrieved)
			case []*Story:
				o.copyMatchingRows(retrieved...)
			case StorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Story or a slice of Story
				// then run the AfterDeleteHooks on the slice
				_, err = Stories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o StorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Stories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o StorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Stories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o StorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Stories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type storyJoins[Q dialect.Joinable] struct {
	typ           string
	CreatedByUser modAs[Q, userColumns]
}

func (j storyJoins[Q]) aliasedAs(alias string) storyJoins[Q] {
	return buildStoryJoins[Q](buildStoryColumns(alias), j.typ)
}

func buildStoryJoins[Q dialect.Joinable](cols storyColumns, typ string) storyJoins[Q] {
	return storyJoins[Q]{
		typ: typ,
		CreatedByUser: modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CreatedBy),
					))
				}

				return mods
			},
		},
	}
}

// CreatedByUser starts a query for related objects on users
func (o *Story) CreatedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.CreatedBy))),
	)...)
}

func (os StorySlice) CreatedByUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkCreatedBy := make(pgtypes.Array[sql.Null[uuid.UUID]], len(os))
	for i, o := range os {
		pkCreatedBy[i] = o.CreatedBy
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCreatedBy), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Story) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CreatedByUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("story cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByUser = rel

		if rel != nil {
			rel.R.CreatedByStories = StorySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("story has no relationship %q", name)
	}
}

type storyPreloader struct {
	CreatedByUser func(...psql.PreloadOption) psql.Preloader
}

func buildStoryPreloader() storyPreloader {
	return storyPreloader{
		CreatedByUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](orm.Relationship{
				Name: "CreatedByUser",
				Sides: []orm.RelSide{
					{
						From: TableNames.Stories,
						To:   TableNames.Users,
						FromColumns: []string{
							ColumnNames.Stories.CreatedBy,
						},
						ToColumns: []string{
							ColumnNames.Users.ID,
						},
					},
				},
			}, Users.Columns().Names(), opts...)
		},
	}
}

type storyThenLoader[Q orm.Loadable] struct {
	CreatedByUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildStoryThenLoader[Q orm.Loadable]() storyThenLoader[Q] {
	type CreatedByUserLoadInterface interface {
		LoadCreatedByUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return storyThenLoader[Q]{
		CreatedByUser: thenLoadBuilder[Q](
			"CreatedByUser",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCreatedByUser loads the story's CreatedByUser into the .R struct
func (o *Story) LoadCreatedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByUser = nil

	related, err := o.CreatedByUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CreatedByStories = StorySlice{o}

	o.R.CreatedByUser = related
	return nil
}

// LoadCreatedByUser loads the story's CreatedByUser into the .R struct
func (os StorySlice) LoadCreatedByUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.CreatedByUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.CreatedBy.V != rel.ID {
				continue
			}

			rel.R.CreatedByStories = append(rel.R.CreatedByStories, o)

			o.R.CreatedByUser = rel
			break
		}
	}

	return nil
}

func attachStoryCreatedByUser0(ctx context.Context, exec bob.Executor, count int, story0 *Story, user1 *User) (*Story, error) {
	setter := &StorySetter{
		CreatedBy: func() *sql.Null[uuid.UUID] {
			v := sql.Null[uuid.UUID]{V: user1.ID, Valid: true}
			return &v
		}(),
	}

	err := story0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachStoryCreatedByUser0: %w", err)
	}

	return story0, nil
}

func (story0 *Story) InsertCreatedByUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachStoryCreatedByUser0(ctx, exec, 1, story0, user1)
	if err != nil {
		return err
	}

	story0.R.CreatedByUser = user1

	user1.R.CreatedByStories = append(user1.R.CreatedByStories, story0)

	return nil
}

func (story0 *Story) AttachCreatedByUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachStoryCreatedByUser0(ctx, exec, 1, story0, user1)
	if err != nil {
		return err
	}

	story0.R.CreatedByUser = user1

	user1.R.CreatedByStories = append(user1.R.CreatedByStories, story0)

	return nil
}
