// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// UserFavouriteStock is an object representing the database table.
type UserFavouriteStock struct {
	ID        uuid.UUID `db:"id,pk" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Symbol    string    `db:"symbol" json:"symbol"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`

	R userFavouriteStockR `db:"-" json:"-"`
}

// UserFavouriteStockSlice is an alias for a slice of pointers to UserFavouriteStock.
// This should almost always be used instead of []*UserFavouriteStock.
type UserFavouriteStockSlice []*UserFavouriteStock

// UserFavouriteStocks contains methods to work with the user_favourite_stocks table
var UserFavouriteStocks = psql.NewTablex[*UserFavouriteStock, UserFavouriteStockSlice, *UserFavouriteStockSetter]("", "user_favourite_stocks")

// UserFavouriteStocksQuery is a query on the user_favourite_stocks table
type UserFavouriteStocksQuery = *psql.ViewQuery[*UserFavouriteStock, UserFavouriteStockSlice]

// UserFavouriteStocksStmt is a prepared statment on user_favourite_stocks
type UserFavouriteStocksStmt = bob.QueryStmt[*UserFavouriteStock, UserFavouriteStockSlice]

// userFavouriteStockR is where relationships are stored.
type userFavouriteStockR struct {
	SymbolStock *Stock `json:"SymbolStock"` // user_favourite_stocks.fk_ufs_stock
	User        *User  `json:"User"`        // user_favourite_stocks.fk_ufs_user
}

// UserFavouriteStockSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserFavouriteStockSetter struct {
	ID        omit.Val[uuid.UUID] `db:"id,pk"`
	UserID    omit.Val[uuid.UUID] `db:"user_id"`
	Symbol    omit.Val[string]    `db:"symbol"`
	Status    omit.Val[string]    `db:"status"`
	CreatedAt omit.Val[time.Time] `db:"created_at"`
	UpdatedAt omit.Val[time.Time] `db:"updated_at"`
}

func (s UserFavouriteStockSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Symbol.IsUnset() {
		vals = append(vals, "symbol")
	}

	if !s.Status.IsUnset() {
		vals = append(vals, "status")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s UserFavouriteStockSetter) Overwrite(t *UserFavouriteStock) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Symbol.IsUnset() {
		t.Symbol, _ = s.Symbol.Get()
	}
	if !s.Status.IsUnset() {
		t.Status, _ = s.Status.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s UserFavouriteStockSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 6)
	if s.ID.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.ID)
	}

	if s.UserID.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.UserID)
	}

	if s.Symbol.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.Symbol)
	}

	if s.Status.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.Status)
	}

	if s.CreatedAt.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.CreatedAt)
	}

	if s.UpdatedAt.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.UpdatedAt)
	}

	return im.Values(vals...)
}

func (s UserFavouriteStockSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s UserFavouriteStockSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.Symbol.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "symbol")...),
			psql.Arg(s.Symbol),
		}})
	}

	if !s.Status.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

type userFavouriteStockColumnNames struct {
	ID        string
	UserID    string
	Symbol    string
	Status    string
	CreatedAt string
	UpdatedAt string
}

type userFavouriteStockRelationshipJoins[Q dialect.Joinable] struct {
	SymbolStock bob.Mod[Q]
	User        bob.Mod[Q]
}

func buildUserFavouriteStockRelationshipJoins[Q dialect.Joinable](ctx context.Context, typ string) userFavouriteStockRelationshipJoins[Q] {
	return userFavouriteStockRelationshipJoins[Q]{
		SymbolStock: userFavouriteStocksJoinSymbolStock[Q](ctx, typ),
		User:        userFavouriteStocksJoinUser[Q](ctx, typ),
	}
}

func userFavouriteStocksJoin[Q dialect.Joinable](ctx context.Context) joinSet[userFavouriteStockRelationshipJoins[Q]] {
	return joinSet[userFavouriteStockRelationshipJoins[Q]]{
		InnerJoin: buildUserFavouriteStockRelationshipJoins[Q](ctx, clause.InnerJoin),
		LeftJoin:  buildUserFavouriteStockRelationshipJoins[Q](ctx, clause.LeftJoin),
		RightJoin: buildUserFavouriteStockRelationshipJoins[Q](ctx, clause.RightJoin),
	}
}

var UserFavouriteStockColumns = struct {
	ID        psql.Expression
	UserID    psql.Expression
	Symbol    psql.Expression
	Status    psql.Expression
	CreatedAt psql.Expression
	UpdatedAt psql.Expression
}{
	ID:        psql.Quote("user_favourite_stocks", "id"),
	UserID:    psql.Quote("user_favourite_stocks", "user_id"),
	Symbol:    psql.Quote("user_favourite_stocks", "symbol"),
	Status:    psql.Quote("user_favourite_stocks", "status"),
	CreatedAt: psql.Quote("user_favourite_stocks", "created_at"),
	UpdatedAt: psql.Quote("user_favourite_stocks", "updated_at"),
}

type userFavouriteStockWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	UserID    psql.WhereMod[Q, uuid.UUID]
	Symbol    psql.WhereMod[Q, string]
	Status    psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func UserFavouriteStockWhere[Q psql.Filterable]() userFavouriteStockWhere[Q] {
	return userFavouriteStockWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](UserFavouriteStockColumns.ID),
		UserID:    psql.Where[Q, uuid.UUID](UserFavouriteStockColumns.UserID),
		Symbol:    psql.Where[Q, string](UserFavouriteStockColumns.Symbol),
		Status:    psql.Where[Q, string](UserFavouriteStockColumns.Status),
		CreatedAt: psql.Where[Q, time.Time](UserFavouriteStockColumns.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](UserFavouriteStockColumns.UpdatedAt),
	}
}

// FindUserFavouriteStock retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserFavouriteStock(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*UserFavouriteStock, error) {
	if len(cols) == 0 {
		return UserFavouriteStocks.Query(
			ctx, exec,
			SelectWhere.UserFavouriteStocks.ID.EQ(IDPK),
		).One()
	}

	return UserFavouriteStocks.Query(
		ctx, exec,
		SelectWhere.UserFavouriteStocks.ID.EQ(IDPK),
		sm.Columns(UserFavouriteStocks.Columns().Only(cols...)),
	).One()
}

// UserFavouriteStockExists checks the presence of a single record by primary key
func UserFavouriteStockExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return UserFavouriteStocks.Query(
		ctx, exec,
		SelectWhere.UserFavouriteStocks.ID.EQ(IDPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the UserFavouriteStock
func (o *UserFavouriteStock) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

// Update uses an executor to update the UserFavouriteStock
func (o *UserFavouriteStock) Update(ctx context.Context, exec bob.Executor, s *UserFavouriteStockSetter) error {
	return UserFavouriteStocks.Update(ctx, exec, s, o)
}

// Delete deletes a single UserFavouriteStock record with an executor
func (o *UserFavouriteStock) Delete(ctx context.Context, exec bob.Executor) error {
	return UserFavouriteStocks.Delete(ctx, exec, o)
}

// Reload refreshes the UserFavouriteStock using the executor
func (o *UserFavouriteStock) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserFavouriteStocks.Query(
		ctx, exec,
		SelectWhere.UserFavouriteStocks.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o UserFavouriteStockSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserFavouriteStockSetter) error {
	return UserFavouriteStocks.Update(ctx, exec, &vals, o...)
}

func (o UserFavouriteStockSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return UserFavouriteStocks.Delete(ctx, exec, o...)
}

func (o UserFavouriteStockSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]uuid.UUID, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.UserFavouriteStocks.ID.In(IDPK...),
	)

	o2, err := UserFavouriteStocks.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func userFavouriteStocksJoinSymbolStock[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Stocks.NameAs(ctx)).On(
			StockColumns.Symbol.EQ(UserFavouriteStockColumns.Symbol),
		),
	}
}

func userFavouriteStocksJoinUser[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Users.NameAs(ctx)).On(
			UserColumns.ID.EQ(UserFavouriteStockColumns.UserID),
		),
	}
}

// SymbolStock starts a query for related objects on stocks
func (o *UserFavouriteStock) SymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) StocksQuery {
	return Stocks.Query(ctx, exec, append(mods,
		sm.Where(StockColumns.Symbol.EQ(psql.Arg(o.Symbol))),
	)...)
}

func (os UserFavouriteStockSlice) SymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) StocksQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.Symbol)
	}

	return Stocks.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(StockColumns.Symbol).In(PKArgs...)),
	)...)
}

// User starts a query for related objects on users
func (o *UserFavouriteStock) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(ctx, exec, append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserFavouriteStockSlice) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.UserID)
	}

	return Users.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserColumns.ID).In(PKArgs...)),
	)...)
}

func (o *UserFavouriteStock) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "SymbolStock":
		rel, ok := retrieved.(*Stock)
		if !ok {
			return fmt.Errorf("userFavouriteStock cannot load %T as %q", retrieved, name)
		}

		o.R.SymbolStock = rel

		if rel != nil {
			rel.R.SymbolUserFavouriteStocks = UserFavouriteStockSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userFavouriteStock cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserFavouriteStocks = UserFavouriteStockSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userFavouriteStock has no relationship %q", name)
	}
}

func PreloadUserFavouriteStockSymbolStock(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*Stock, StockSlice](orm.Relationship{
		Name: "SymbolStock",
		Sides: []orm.RelSide{
			{
				From: "user_favourite_stocks",
				To:   TableNames.Stocks,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Stocks.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.UserFavouriteStocks.Symbol,
				},
				ToColumns: []string{
					ColumnNames.Stocks.Symbol,
				},
			},
		},
	}, Stocks.Columns().Names(), opts...)
}

func ThenLoadUserFavouriteStockSymbolStock(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserFavouriteStockSymbolStock(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserFavouriteStockSymbolStock", retrieved)
		}

		err := loader.LoadUserFavouriteStockSymbolStock(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserFavouriteStockSymbolStock loads the userFavouriteStock's SymbolStock into the .R struct
func (o *UserFavouriteStock) LoadUserFavouriteStockSymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SymbolStock = nil

	related, err := o.SymbolStock(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.SymbolUserFavouriteStocks = UserFavouriteStockSlice{o}

	o.R.SymbolStock = related
	return nil
}

// LoadUserFavouriteStockSymbolStock loads the userFavouriteStock's SymbolStock into the .R struct
func (os UserFavouriteStockSlice) LoadUserFavouriteStockSymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	stocks, err := os.SymbolStock(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range stocks {
			if o.Symbol != rel.Symbol {
				continue
			}

			rel.R.SymbolUserFavouriteStocks = append(rel.R.SymbolUserFavouriteStocks, o)

			o.R.SymbolStock = rel
			break
		}
	}

	return nil
}

func PreloadUserFavouriteStockUser(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*User, UserSlice](orm.Relationship{
		Name: "User",
		Sides: []orm.RelSide{
			{
				From: "user_favourite_stocks",
				To:   TableNames.Users,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Users.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.UserFavouriteStocks.UserID,
				},
				ToColumns: []string{
					ColumnNames.Users.ID,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadUserFavouriteStockUser(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserFavouriteStockUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserFavouriteStockUser", retrieved)
		}

		err := loader.LoadUserFavouriteStockUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserFavouriteStockUser loads the userFavouriteStock's User into the .R struct
func (o *UserFavouriteStock) LoadUserFavouriteStockUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.UserFavouriteStocks = UserFavouriteStockSlice{o}

	o.R.User = related
	return nil
}

// LoadUserFavouriteStockUser loads the userFavouriteStock's User into the .R struct
func (os UserFavouriteStockSlice) LoadUserFavouriteStockUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.UserFavouriteStocks = append(rel.R.UserFavouriteStocks, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachUserFavouriteStockSymbolStock0(ctx context.Context, exec bob.Executor, count int, userFavouriteStock0 *UserFavouriteStock, stock1 *Stock) (*UserFavouriteStock, error) {
	setter := &UserFavouriteStockSetter{
		Symbol: omit.From(stock1.Symbol),
	}

	err := UserFavouriteStocks.Update(ctx, exec, setter, userFavouriteStock0)
	if err != nil {
		return nil, fmt.Errorf("attachUserFavouriteStockSymbolStock0: %w", err)
	}

	return userFavouriteStock0, nil
}

func (userFavouriteStock0 *UserFavouriteStock) InsertSymbolStock(ctx context.Context, exec bob.Executor, related *StockSetter) error {
	stock1, err := Stocks.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserFavouriteStockSymbolStock0(ctx, exec, 1, userFavouriteStock0, stock1)
	if err != nil {
		return err
	}

	userFavouriteStock0.R.SymbolStock = stock1

	stock1.R.SymbolUserFavouriteStocks = append(stock1.R.SymbolUserFavouriteStocks, userFavouriteStock0)

	return nil
}

func (userFavouriteStock0 *UserFavouriteStock) AttachSymbolStock(ctx context.Context, exec bob.Executor, stock1 *Stock) error {
	var err error

	_, err = attachUserFavouriteStockSymbolStock0(ctx, exec, 1, userFavouriteStock0, stock1)
	if err != nil {
		return err
	}

	userFavouriteStock0.R.SymbolStock = stock1

	stock1.R.SymbolUserFavouriteStocks = append(stock1.R.SymbolUserFavouriteStocks, userFavouriteStock0)

	return nil
}

func attachUserFavouriteStockUser0(ctx context.Context, exec bob.Executor, count int, userFavouriteStock0 *UserFavouriteStock, user1 *User) (*UserFavouriteStock, error) {
	setter := &UserFavouriteStockSetter{
		UserID: omit.From(user1.ID),
	}

	err := UserFavouriteStocks.Update(ctx, exec, setter, userFavouriteStock0)
	if err != nil {
		return nil, fmt.Errorf("attachUserFavouriteStockUser0: %w", err)
	}

	return userFavouriteStock0, nil
}

func (userFavouriteStock0 *UserFavouriteStock) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserFavouriteStockUser0(ctx, exec, 1, userFavouriteStock0, user1)
	if err != nil {
		return err
	}

	userFavouriteStock0.R.User = user1

	user1.R.UserFavouriteStocks = append(user1.R.UserFavouriteStocks, userFavouriteStock0)

	return nil
}

func (userFavouriteStock0 *UserFavouriteStock) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserFavouriteStockUser0(ctx, exec, 1, userFavouriteStock0, user1)
	if err != nil {
		return err
	}

	userFavouriteStock0.R.User = user1

	user1.R.UserFavouriteStocks = append(user1.R.UserFavouriteStocks, userFavouriteStock0)

	return nil
}
