// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
)

// User is an object representing the database table.
type User struct {
	ID        uuid.UUID        `db:"id,pk" json:"id"`
	FirstName null.Val[string] `db:"first_name" json:"first_name"`
	LastName  null.Val[string] `db:"last_name" json:"last_name"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	Email     string           `db:"email" json:"email"`
	IsActive  bool             `db:"is_active" json:"is_active"`
	UpdatedAt time.Time        `db:"updated_at" json:"updated_at"`
	CreatedAt time.Time        `db:"created_at" json:"created_at"`

	R userR `db:"-" json:"-"`
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users")

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// UsersStmt is a prepared statment on users
type UsersStmt = bob.QueryStmt[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	UserCodes           UserCodeSlice           `json:"UserCodes"`           // user_codes.fk__user_codes__users
	UserFavouriteStocks UserFavouriteStockSlice `json:"UserFavouriteStocks"` // user_favourite_stocks.fk_ufs_user
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID        omit.Val[uuid.UUID]  `db:"id,pk"`
	FirstName omitnull.Val[string] `db:"first_name"`
	LastName  omitnull.Val[string] `db:"last_name"`
	Username  omit.Val[string]     `db:"username"`
	Password  omit.Val[string]     `db:"password"`
	Email     omit.Val[string]     `db:"email"`
	IsActive  omit.Val[bool]       `db:"is_active"`
	UpdatedAt omit.Val[time.Time]  `db:"updated_at"`
	CreatedAt omit.Val[time.Time]  `db:"created_at"`
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.FirstName.IsUnset() {
		vals = append(vals, "first_name")
	}

	if !s.LastName.IsUnset() {
		vals = append(vals, "last_name")
	}

	if !s.Username.IsUnset() {
		vals = append(vals, "username")
	}

	if !s.Password.IsUnset() {
		vals = append(vals, "password")
	}

	if !s.Email.IsUnset() {
		vals = append(vals, "email")
	}

	if !s.IsActive.IsUnset() {
		vals = append(vals, "is_active")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.FirstName.IsUnset() {
		t.FirstName, _ = s.FirstName.GetNull()
	}
	if !s.LastName.IsUnset() {
		t.LastName, _ = s.LastName.GetNull()
	}
	if !s.Username.IsUnset() {
		t.Username, _ = s.Username.Get()
	}
	if !s.Password.IsUnset() {
		t.Password, _ = s.Password.Get()
	}
	if !s.Email.IsUnset() {
		t.Email, _ = s.Email.Get()
	}
	if !s.IsActive.IsUnset() {
		t.IsActive, _ = s.IsActive.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
}

func (s UserSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 9)
	if s.ID.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.ID)
	}

	if s.FirstName.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.FirstName)
	}

	if s.LastName.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.LastName)
	}

	if s.Username.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.Username)
	}

	if s.Password.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.Password)
	}

	if s.Email.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.Email)
	}

	if s.IsActive.IsUnset() {
		vals[6] = psql.Raw("DEFAULT")
	} else {
		vals[6] = psql.Arg(s.IsActive)
	}

	if s.UpdatedAt.IsUnset() {
		vals[7] = psql.Raw("DEFAULT")
	} else {
		vals[7] = psql.Arg(s.UpdatedAt)
	}

	if s.CreatedAt.IsUnset() {
		vals[8] = psql.Raw("DEFAULT")
	} else {
		vals[8] = psql.Arg(s.CreatedAt)
	}

	return im.Values(vals...)
}

func (s UserSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.FirstName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "first_name")...),
			psql.Arg(s.FirstName),
		}})
	}

	if !s.LastName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_name")...),
			psql.Arg(s.LastName),
		}})
	}

	if !s.Username.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "username")...),
			psql.Arg(s.Username),
		}})
	}

	if !s.Password.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password")...),
			psql.Arg(s.Password),
		}})
	}

	if !s.Email.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if !s.IsActive.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

type userColumnNames struct {
	ID        string
	FirstName string
	LastName  string
	Username  string
	Password  string
	Email     string
	IsActive  string
	UpdatedAt string
	CreatedAt string
}

type userRelationshipJoins[Q dialect.Joinable] struct {
	UserCodes           bob.Mod[Q]
	UserFavouriteStocks bob.Mod[Q]
}

func buildUserRelationshipJoins[Q dialect.Joinable](ctx context.Context, typ string) userRelationshipJoins[Q] {
	return userRelationshipJoins[Q]{
		UserCodes:           usersJoinUserCodes[Q](ctx, typ),
		UserFavouriteStocks: usersJoinUserFavouriteStocks[Q](ctx, typ),
	}
}

func usersJoin[Q dialect.Joinable](ctx context.Context) joinSet[userRelationshipJoins[Q]] {
	return joinSet[userRelationshipJoins[Q]]{
		InnerJoin: buildUserRelationshipJoins[Q](ctx, clause.InnerJoin),
		LeftJoin:  buildUserRelationshipJoins[Q](ctx, clause.LeftJoin),
		RightJoin: buildUserRelationshipJoins[Q](ctx, clause.RightJoin),
	}
}

var UserColumns = struct {
	ID        psql.Expression
	FirstName psql.Expression
	LastName  psql.Expression
	Username  psql.Expression
	Password  psql.Expression
	Email     psql.Expression
	IsActive  psql.Expression
	UpdatedAt psql.Expression
	CreatedAt psql.Expression
}{
	ID:        psql.Quote("users", "id"),
	FirstName: psql.Quote("users", "first_name"),
	LastName:  psql.Quote("users", "last_name"),
	Username:  psql.Quote("users", "username"),
	Password:  psql.Quote("users", "password"),
	Email:     psql.Quote("users", "email"),
	IsActive:  psql.Quote("users", "is_active"),
	UpdatedAt: psql.Quote("users", "updated_at"),
	CreatedAt: psql.Quote("users", "created_at"),
}

type userWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	FirstName psql.WhereNullMod[Q, string]
	LastName  psql.WhereNullMod[Q, string]
	Username  psql.WhereMod[Q, string]
	Password  psql.WhereMod[Q, string]
	Email     psql.WhereMod[Q, string]
	IsActive  psql.WhereMod[Q, bool]
	UpdatedAt psql.WhereMod[Q, time.Time]
	CreatedAt psql.WhereMod[Q, time.Time]
}

func UserWhere[Q psql.Filterable]() userWhere[Q] {
	return userWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](UserColumns.ID),
		FirstName: psql.WhereNull[Q, string](UserColumns.FirstName),
		LastName:  psql.WhereNull[Q, string](UserColumns.LastName),
		Username:  psql.Where[Q, string](UserColumns.Username),
		Password:  psql.Where[Q, string](UserColumns.Password),
		Email:     psql.Where[Q, string](UserColumns.Email),
		IsActive:  psql.Where[Q, bool](UserColumns.IsActive),
		UpdatedAt: psql.Where[Q, time.Time](UserColumns.UpdatedAt),
		CreatedAt: psql.Where[Q, time.Time](UserColumns.CreatedAt),
	}
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			ctx, exec,
			SelectWhere.Users.ID.EQ(IDPK),
		).One()
	}

	return Users.Query(
		ctx, exec,
		SelectWhere.Users.ID.EQ(IDPK),
		sm.Columns(Users.Columns().Only(cols...)),
	).One()
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Users.Query(
		ctx, exec,
		SelectWhere.Users.ID.EQ(IDPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the User
func (o *User) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	return Users.Update(ctx, exec, s, o)
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	return Users.Delete(ctx, exec, o)
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		ctx, exec,
		SelectWhere.Users.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	return Users.Update(ctx, exec, &vals, o...)
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return Users.Delete(ctx, exec, o...)
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]uuid.UUID, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.Users.ID.In(IDPK...),
	)

	o2, err := Users.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func usersJoinUserCodes[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, UserCodes.NameAs(ctx)).On(
			UserCodeColumns.UserID.EQ(UserColumns.ID),
		),
	}
}

func usersJoinUserFavouriteStocks[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, UserFavouriteStocks.NameAs(ctx)).On(
			UserFavouriteStockColumns.UserID.EQ(UserColumns.ID),
		),
	}
}

// UserCodes starts a query for related objects on user_codes
func (o *User) UserCodes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserCodesQuery {
	return UserCodes.Query(ctx, exec, append(mods,
		sm.Where(UserCodeColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) UserCodes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserCodesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return UserCodes.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserCodeColumns.UserID).In(PKArgs...)),
	)...)
}

// UserFavouriteStocks starts a query for related objects on user_favourite_stocks
func (o *User) UserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserFavouriteStocksQuery {
	return UserFavouriteStocks.Query(ctx, exec, append(mods,
		sm.Where(UserFavouriteStockColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) UserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UserFavouriteStocksQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return UserFavouriteStocks.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserFavouriteStockColumns.UserID).In(PKArgs...)),
	)...)
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UserCodes":
		rels, ok := retrieved.(UserCodeSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserCodes = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "UserFavouriteStocks":
		rels, ok := retrieved.(UserFavouriteStockSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserFavouriteStocks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

func ThenLoadUserUserCodes(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserUserCodes(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserUserCodes", retrieved)
		}

		err := loader.LoadUserUserCodes(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserUserCodes loads the user's UserCodes into the .R struct
func (o *User) LoadUserUserCodes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserCodes = nil

	related, err := o.UserCodes(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.UserCodes = related
	return nil
}

// LoadUserUserCodes loads the user's UserCodes into the .R struct
func (os UserSlice) LoadUserUserCodes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userCodes, err := os.UserCodes(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.UserCodes = nil
	}

	for _, o := range os {
		for _, rel := range userCodes {
			if o.ID != rel.UserID {
				continue
			}

			rel.R.User = o

			o.R.UserCodes = append(o.R.UserCodes, rel)
		}
	}

	return nil
}

func ThenLoadUserUserFavouriteStocks(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserUserFavouriteStocks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserUserFavouriteStocks", retrieved)
		}

		err := loader.LoadUserUserFavouriteStocks(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserUserFavouriteStocks loads the user's UserFavouriteStocks into the .R struct
func (o *User) LoadUserUserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserFavouriteStocks = nil

	related, err := o.UserFavouriteStocks(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.UserFavouriteStocks = related
	return nil
}

// LoadUserUserFavouriteStocks loads the user's UserFavouriteStocks into the .R struct
func (os UserSlice) LoadUserUserFavouriteStocks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userFavouriteStocks, err := os.UserFavouriteStocks(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.UserFavouriteStocks = nil
	}

	for _, o := range os {
		for _, rel := range userFavouriteStocks {
			if o.ID != rel.UserID {
				continue
			}

			rel.R.User = o

			o.R.UserFavouriteStocks = append(o.R.UserFavouriteStocks, rel)
		}
	}

	return nil
}

func insertUserUserCodes0(ctx context.Context, exec bob.Executor, userCodes1 []*UserCodeSetter, user0 *User) (UserCodeSlice, error) {
	for i := range userCodes1 {
		userCodes1[i].UserID = omit.From(user0.ID)
	}

	ret, err := UserCodes.InsertMany(ctx, exec, userCodes1...)
	if err != nil {
		return ret, fmt.Errorf("insertUserUserCodes0: %w", err)
	}

	return ret, nil
}

func attachUserUserCodes0(ctx context.Context, exec bob.Executor, count int, userCodes1 UserCodeSlice, user0 *User) (UserCodeSlice, error) {
	setter := &UserCodeSetter{
		UserID: omit.From(user0.ID),
	}

	err := UserCodes.Update(ctx, exec, setter, userCodes1...)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserCodes0: %w", err)
	}

	return userCodes1, nil
}

func (user0 *User) InsertUserCodes(ctx context.Context, exec bob.Executor, related ...*UserCodeSetter) error {
	if len(related) == 0 {
		return nil
	}

	userCodes1, err := insertUserUserCodes0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UserCodes = append(user0.R.UserCodes, userCodes1...)

	for _, rel := range userCodes1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachUserCodes(ctx context.Context, exec bob.Executor, related ...*UserCode) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userCodes1 := UserCodeSlice(related)

	_, err = attachUserUserCodes0(ctx, exec, len(related), userCodes1, user0)
	if err != nil {
		return err
	}

	user0.R.UserCodes = append(user0.R.UserCodes, userCodes1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserUserFavouriteStocks0(ctx context.Context, exec bob.Executor, userFavouriteStocks1 []*UserFavouriteStockSetter, user0 *User) (UserFavouriteStockSlice, error) {
	for i := range userFavouriteStocks1 {
		userFavouriteStocks1[i].UserID = omit.From(user0.ID)
	}

	ret, err := UserFavouriteStocks.InsertMany(ctx, exec, userFavouriteStocks1...)
	if err != nil {
		return ret, fmt.Errorf("insertUserUserFavouriteStocks0: %w", err)
	}

	return ret, nil
}

func attachUserUserFavouriteStocks0(ctx context.Context, exec bob.Executor, count int, userFavouriteStocks1 UserFavouriteStockSlice, user0 *User) (UserFavouriteStockSlice, error) {
	setter := &UserFavouriteStockSetter{
		UserID: omit.From(user0.ID),
	}

	err := UserFavouriteStocks.Update(ctx, exec, setter, userFavouriteStocks1...)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserFavouriteStocks0: %w", err)
	}

	return userFavouriteStocks1, nil
}

func (user0 *User) InsertUserFavouriteStocks(ctx context.Context, exec bob.Executor, related ...*UserFavouriteStockSetter) error {
	if len(related) == 0 {
		return nil
	}

	userFavouriteStocks1, err := insertUserUserFavouriteStocks0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UserFavouriteStocks = append(user0.R.UserFavouriteStocks, userFavouriteStocks1...)

	for _, rel := range userFavouriteStocks1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachUserFavouriteStocks(ctx context.Context, exec bob.Executor, related ...*UserFavouriteStock) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userFavouriteStocks1 := UserFavouriteStockSlice(related)

	_, err = attachUserUserFavouriteStocks0(ctx, exec, len(related), userFavouriteStocks1, user0)
	if err != nil {
		return err
	}

	user0.R.UserFavouriteStocks = append(user0.R.UserFavouriteStocks, userFavouriteStocks1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}
