// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// UserStockAlert is an object representing the database table.
type UserStockAlert struct {
	ID             uuid.UUID                 `db:"id,pk" json:"id"`
	UserID         uuid.UUID                 `db:"user_id" json:"user_id"`
	Symbol         string                    `db:"symbol" json:"symbol"`
	HighThreshold  null.Val[decimal.Decimal] `db:"high_threshold" json:"high_threshold"`
	LowThreshold   null.Val[decimal.Decimal] `db:"low_threshold" json:"low_threshold"`
	LastNotifiedAt null.Val[time.Time]       `db:"last_notified_at" json:"last_notified_at"`
	IsActive       bool                      `db:"is_active" json:"is_active"`
	CreatedAt      time.Time                 `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time                 `db:"updated_at" json:"updated_at"`

	R userStockAlertR `db:"-" json:"-"`
}

// UserStockAlertSlice is an alias for a slice of pointers to UserStockAlert.
// This should almost always be used instead of []*UserStockAlert.
type UserStockAlertSlice []*UserStockAlert

// UserStockAlerts contains methods to work with the user_stock_alerts table
var UserStockAlerts = psql.NewTablex[*UserStockAlert, UserStockAlertSlice, *UserStockAlertSetter]("", "user_stock_alerts")

// UserStockAlertsQuery is a query on the user_stock_alerts table
type UserStockAlertsQuery = *psql.ViewQuery[*UserStockAlert, UserStockAlertSlice]

// UserStockAlertsStmt is a prepared statment on user_stock_alerts
type UserStockAlertsStmt = bob.QueryStmt[*UserStockAlert, UserStockAlertSlice]

// userStockAlertR is where relationships are stored.
type userStockAlertR struct {
	SymbolStock *Stock `json:"SymbolStock"` // user_stock_alerts.fk_usa_stock
	User        *User  `json:"User"`        // user_stock_alerts.fk_usa_user
}

// UserStockAlertSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserStockAlertSetter struct {
	ID             omit.Val[uuid.UUID]           `db:"id,pk"`
	UserID         omit.Val[uuid.UUID]           `db:"user_id"`
	Symbol         omit.Val[string]              `db:"symbol"`
	HighThreshold  omitnull.Val[decimal.Decimal] `db:"high_threshold"`
	LowThreshold   omitnull.Val[decimal.Decimal] `db:"low_threshold"`
	LastNotifiedAt omitnull.Val[time.Time]       `db:"last_notified_at"`
	IsActive       omit.Val[bool]                `db:"is_active"`
	CreatedAt      omit.Val[time.Time]           `db:"created_at"`
	UpdatedAt      omit.Val[time.Time]           `db:"updated_at"`
}

func (s UserStockAlertSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Symbol.IsUnset() {
		vals = append(vals, "symbol")
	}

	if !s.HighThreshold.IsUnset() {
		vals = append(vals, "high_threshold")
	}

	if !s.LowThreshold.IsUnset() {
		vals = append(vals, "low_threshold")
	}

	if !s.LastNotifiedAt.IsUnset() {
		vals = append(vals, "last_notified_at")
	}

	if !s.IsActive.IsUnset() {
		vals = append(vals, "is_active")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s UserStockAlertSetter) Overwrite(t *UserStockAlert) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Symbol.IsUnset() {
		t.Symbol, _ = s.Symbol.Get()
	}
	if !s.HighThreshold.IsUnset() {
		t.HighThreshold, _ = s.HighThreshold.GetNull()
	}
	if !s.LowThreshold.IsUnset() {
		t.LowThreshold, _ = s.LowThreshold.GetNull()
	}
	if !s.LastNotifiedAt.IsUnset() {
		t.LastNotifiedAt, _ = s.LastNotifiedAt.GetNull()
	}
	if !s.IsActive.IsUnset() {
		t.IsActive, _ = s.IsActive.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s UserStockAlertSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 9)
	if s.ID.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.ID)
	}

	if s.UserID.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.UserID)
	}

	if s.Symbol.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.Symbol)
	}

	if s.HighThreshold.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.HighThreshold)
	}

	if s.LowThreshold.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.LowThreshold)
	}

	if s.LastNotifiedAt.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.LastNotifiedAt)
	}

	if s.IsActive.IsUnset() {
		vals[6] = psql.Raw("DEFAULT")
	} else {
		vals[6] = psql.Arg(s.IsActive)
	}

	if s.CreatedAt.IsUnset() {
		vals[7] = psql.Raw("DEFAULT")
	} else {
		vals[7] = psql.Arg(s.CreatedAt)
	}

	if s.UpdatedAt.IsUnset() {
		vals[8] = psql.Raw("DEFAULT")
	} else {
		vals[8] = psql.Arg(s.UpdatedAt)
	}

	return im.Values(vals...)
}

func (s UserStockAlertSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s UserStockAlertSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.Symbol.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "symbol")...),
			psql.Arg(s.Symbol),
		}})
	}

	if !s.HighThreshold.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "high_threshold")...),
			psql.Arg(s.HighThreshold),
		}})
	}

	if !s.LowThreshold.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "low_threshold")...),
			psql.Arg(s.LowThreshold),
		}})
	}

	if !s.LastNotifiedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_notified_at")...),
			psql.Arg(s.LastNotifiedAt),
		}})
	}

	if !s.IsActive.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

type userStockAlertColumnNames struct {
	ID             string
	UserID         string
	Symbol         string
	HighThreshold  string
	LowThreshold   string
	LastNotifiedAt string
	IsActive       string
	CreatedAt      string
	UpdatedAt      string
}

type userStockAlertRelationshipJoins[Q dialect.Joinable] struct {
	SymbolStock bob.Mod[Q]
	User        bob.Mod[Q]
}

func buildUserStockAlertRelationshipJoins[Q dialect.Joinable](ctx context.Context, typ string) userStockAlertRelationshipJoins[Q] {
	return userStockAlertRelationshipJoins[Q]{
		SymbolStock: userStockAlertsJoinSymbolStock[Q](ctx, typ),
		User:        userStockAlertsJoinUser[Q](ctx, typ),
	}
}

func userStockAlertsJoin[Q dialect.Joinable](ctx context.Context) joinSet[userStockAlertRelationshipJoins[Q]] {
	return joinSet[userStockAlertRelationshipJoins[Q]]{
		InnerJoin: buildUserStockAlertRelationshipJoins[Q](ctx, clause.InnerJoin),
		LeftJoin:  buildUserStockAlertRelationshipJoins[Q](ctx, clause.LeftJoin),
		RightJoin: buildUserStockAlertRelationshipJoins[Q](ctx, clause.RightJoin),
	}
}

var UserStockAlertColumns = struct {
	ID             psql.Expression
	UserID         psql.Expression
	Symbol         psql.Expression
	HighThreshold  psql.Expression
	LowThreshold   psql.Expression
	LastNotifiedAt psql.Expression
	IsActive       psql.Expression
	CreatedAt      psql.Expression
	UpdatedAt      psql.Expression
}{
	ID:             psql.Quote("user_stock_alerts", "id"),
	UserID:         psql.Quote("user_stock_alerts", "user_id"),
	Symbol:         psql.Quote("user_stock_alerts", "symbol"),
	HighThreshold:  psql.Quote("user_stock_alerts", "high_threshold"),
	LowThreshold:   psql.Quote("user_stock_alerts", "low_threshold"),
	LastNotifiedAt: psql.Quote("user_stock_alerts", "last_notified_at"),
	IsActive:       psql.Quote("user_stock_alerts", "is_active"),
	CreatedAt:      psql.Quote("user_stock_alerts", "created_at"),
	UpdatedAt:      psql.Quote("user_stock_alerts", "updated_at"),
}

type userStockAlertWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, uuid.UUID]
	UserID         psql.WhereMod[Q, uuid.UUID]
	Symbol         psql.WhereMod[Q, string]
	HighThreshold  psql.WhereNullMod[Q, decimal.Decimal]
	LowThreshold   psql.WhereNullMod[Q, decimal.Decimal]
	LastNotifiedAt psql.WhereNullMod[Q, time.Time]
	IsActive       psql.WhereMod[Q, bool]
	CreatedAt      psql.WhereMod[Q, time.Time]
	UpdatedAt      psql.WhereMod[Q, time.Time]
}

func UserStockAlertWhere[Q psql.Filterable]() userStockAlertWhere[Q] {
	return userStockAlertWhere[Q]{
		ID:             psql.Where[Q, uuid.UUID](UserStockAlertColumns.ID),
		UserID:         psql.Where[Q, uuid.UUID](UserStockAlertColumns.UserID),
		Symbol:         psql.Where[Q, string](UserStockAlertColumns.Symbol),
		HighThreshold:  psql.WhereNull[Q, decimal.Decimal](UserStockAlertColumns.HighThreshold),
		LowThreshold:   psql.WhereNull[Q, decimal.Decimal](UserStockAlertColumns.LowThreshold),
		LastNotifiedAt: psql.WhereNull[Q, time.Time](UserStockAlertColumns.LastNotifiedAt),
		IsActive:       psql.Where[Q, bool](UserStockAlertColumns.IsActive),
		CreatedAt:      psql.Where[Q, time.Time](UserStockAlertColumns.CreatedAt),
		UpdatedAt:      psql.Where[Q, time.Time](UserStockAlertColumns.UpdatedAt),
	}
}

// FindUserStockAlert retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserStockAlert(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*UserStockAlert, error) {
	if len(cols) == 0 {
		return UserStockAlerts.Query(
			ctx, exec,
			SelectWhere.UserStockAlerts.ID.EQ(IDPK),
		).One()
	}

	return UserStockAlerts.Query(
		ctx, exec,
		SelectWhere.UserStockAlerts.ID.EQ(IDPK),
		sm.Columns(UserStockAlerts.Columns().Only(cols...)),
	).One()
}

// UserStockAlertExists checks the presence of a single record by primary key
func UserStockAlertExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return UserStockAlerts.Query(
		ctx, exec,
		SelectWhere.UserStockAlerts.ID.EQ(IDPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the UserStockAlert
func (o *UserStockAlert) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

// Update uses an executor to update the UserStockAlert
func (o *UserStockAlert) Update(ctx context.Context, exec bob.Executor, s *UserStockAlertSetter) error {
	return UserStockAlerts.Update(ctx, exec, s, o)
}

// Delete deletes a single UserStockAlert record with an executor
func (o *UserStockAlert) Delete(ctx context.Context, exec bob.Executor) error {
	return UserStockAlerts.Delete(ctx, exec, o)
}

// Reload refreshes the UserStockAlert using the executor
func (o *UserStockAlert) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserStockAlerts.Query(
		ctx, exec,
		SelectWhere.UserStockAlerts.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o UserStockAlertSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserStockAlertSetter) error {
	return UserStockAlerts.Update(ctx, exec, &vals, o...)
}

func (o UserStockAlertSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return UserStockAlerts.Delete(ctx, exec, o...)
}

func (o UserStockAlertSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]uuid.UUID, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.UserStockAlerts.ID.In(IDPK...),
	)

	o2, err := UserStockAlerts.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func userStockAlertsJoinSymbolStock[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Stocks.NameAs(ctx)).On(
			StockColumns.Symbol.EQ(UserStockAlertColumns.Symbol),
		),
	}
}

func userStockAlertsJoinUser[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Users.NameAs(ctx)).On(
			UserColumns.ID.EQ(UserStockAlertColumns.UserID),
		),
	}
}

// SymbolStock starts a query for related objects on stocks
func (o *UserStockAlert) SymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) StocksQuery {
	return Stocks.Query(ctx, exec, append(mods,
		sm.Where(StockColumns.Symbol.EQ(psql.Arg(o.Symbol))),
	)...)
}

func (os UserStockAlertSlice) SymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) StocksQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.Symbol)
	}

	return Stocks.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(StockColumns.Symbol).In(PKArgs...)),
	)...)
}

// User starts a query for related objects on users
func (o *UserStockAlert) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(ctx, exec, append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserStockAlertSlice) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.UserID)
	}

	return Users.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserColumns.ID).In(PKArgs...)),
	)...)
}

func (o *UserStockAlert) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "SymbolStock":
		rel, ok := retrieved.(*Stock)
		if !ok {
			return fmt.Errorf("userStockAlert cannot load %T as %q", retrieved, name)
		}

		o.R.SymbolStock = rel

		if rel != nil {
			rel.R.SymbolUserStockAlerts = UserStockAlertSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userStockAlert cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserStockAlerts = UserStockAlertSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userStockAlert has no relationship %q", name)
	}
}

func PreloadUserStockAlertSymbolStock(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*Stock, StockSlice](orm.Relationship{
		Name: "SymbolStock",
		Sides: []orm.RelSide{
			{
				From: "user_stock_alerts",
				To:   TableNames.Stocks,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Stocks.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.UserStockAlerts.Symbol,
				},
				ToColumns: []string{
					ColumnNames.Stocks.Symbol,
				},
			},
		},
	}, Stocks.Columns().Names(), opts...)
}

func ThenLoadUserStockAlertSymbolStock(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserStockAlertSymbolStock(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserStockAlertSymbolStock", retrieved)
		}

		err := loader.LoadUserStockAlertSymbolStock(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserStockAlertSymbolStock loads the userStockAlert's SymbolStock into the .R struct
func (o *UserStockAlert) LoadUserStockAlertSymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SymbolStock = nil

	related, err := o.SymbolStock(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.SymbolUserStockAlerts = UserStockAlertSlice{o}

	o.R.SymbolStock = related
	return nil
}

// LoadUserStockAlertSymbolStock loads the userStockAlert's SymbolStock into the .R struct
func (os UserStockAlertSlice) LoadUserStockAlertSymbolStock(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	stocks, err := os.SymbolStock(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range stocks {
			if o.Symbol != rel.Symbol {
				continue
			}

			rel.R.SymbolUserStockAlerts = append(rel.R.SymbolUserStockAlerts, o)

			o.R.SymbolStock = rel
			break
		}
	}

	return nil
}

func PreloadUserStockAlertUser(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*User, UserSlice](orm.Relationship{
		Name: "User",
		Sides: []orm.RelSide{
			{
				From: "user_stock_alerts",
				To:   TableNames.Users,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Users.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.UserStockAlerts.UserID,
				},
				ToColumns: []string{
					ColumnNames.Users.ID,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadUserStockAlertUser(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserStockAlertUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserStockAlertUser", retrieved)
		}

		err := loader.LoadUserStockAlertUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserStockAlertUser loads the userStockAlert's User into the .R struct
func (o *UserStockAlert) LoadUserStockAlertUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.UserStockAlerts = UserStockAlertSlice{o}

	o.R.User = related
	return nil
}

// LoadUserStockAlertUser loads the userStockAlert's User into the .R struct
func (os UserStockAlertSlice) LoadUserStockAlertUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.UserStockAlerts = append(rel.R.UserStockAlerts, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachUserStockAlertSymbolStock0(ctx context.Context, exec bob.Executor, count int, userStockAlert0 *UserStockAlert, stock1 *Stock) (*UserStockAlert, error) {
	setter := &UserStockAlertSetter{
		Symbol: omit.From(stock1.Symbol),
	}

	err := UserStockAlerts.Update(ctx, exec, setter, userStockAlert0)
	if err != nil {
		return nil, fmt.Errorf("attachUserStockAlertSymbolStock0: %w", err)
	}

	return userStockAlert0, nil
}

func (userStockAlert0 *UserStockAlert) InsertSymbolStock(ctx context.Context, exec bob.Executor, related *StockSetter) error {
	stock1, err := Stocks.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserStockAlertSymbolStock0(ctx, exec, 1, userStockAlert0, stock1)
	if err != nil {
		return err
	}

	userStockAlert0.R.SymbolStock = stock1

	stock1.R.SymbolUserStockAlerts = append(stock1.R.SymbolUserStockAlerts, userStockAlert0)

	return nil
}

func (userStockAlert0 *UserStockAlert) AttachSymbolStock(ctx context.Context, exec bob.Executor, stock1 *Stock) error {
	var err error

	_, err = attachUserStockAlertSymbolStock0(ctx, exec, 1, userStockAlert0, stock1)
	if err != nil {
		return err
	}

	userStockAlert0.R.SymbolStock = stock1

	stock1.R.SymbolUserStockAlerts = append(stock1.R.SymbolUserStockAlerts, userStockAlert0)

	return nil
}

func attachUserStockAlertUser0(ctx context.Context, exec bob.Executor, count int, userStockAlert0 *UserStockAlert, user1 *User) (*UserStockAlert, error) {
	setter := &UserStockAlertSetter{
		UserID: omit.From(user1.ID),
	}

	err := UserStockAlerts.Update(ctx, exec, setter, userStockAlert0)
	if err != nil {
		return nil, fmt.Errorf("attachUserStockAlertUser0: %w", err)
	}

	return userStockAlert0, nil
}

func (userStockAlert0 *UserStockAlert) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserStockAlertUser0(ctx, exec, 1, userStockAlert0, user1)
	if err != nil {
		return err
	}

	userStockAlert0.R.User = user1

	user1.R.UserStockAlerts = append(user1.R.UserStockAlerts, userStockAlert0)

	return nil
}

func (userStockAlert0 *UserStockAlert) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserStockAlertUser0(ctx, exec, 1, userStockAlert0, user1)
	if err != nil {
		return err
	}

	userStockAlert0.R.User = user1

	user1.R.UserStockAlerts = append(user1.R.UserStockAlerts, userStockAlert0)

	return nil
}
