// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// User is an object representing the database table.
type User struct {
	ID        uuid.UUID        `db:"id,pk" json:"id"`
	FirstName sql.Null[string] `db:"first_name" json:"first_name"`
	LastName  sql.Null[string] `db:"last_name" json:"last_name"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	Email     string           `db:"email" json:"email"`
	IsActive  bool             `db:"is_active" json:"is_active"`
	UpdatedAt time.Time        `db:"updated_at" json:"updated_at"`
	CreatedAt time.Time        `db:"created_at" json:"created_at"`

	R userR `db:"-" json:"-"`
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users")

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	CreatedByChapters ChapterSlice  `json:"CreatedByChapters"` // chapters.fk__chapters__users
	CreatedByStories  StorySlice    `json:"CreatedByStories"`  // stories.fk__stories__users
	UserCodes         UserCodeSlice `json:"UserCodes"`         // user_codes.fk__user_codes__users
}

type userColumnNames struct {
	ID        string
	FirstName string
	LastName  string
	Username  string
	Password  string
	Email     string
	IsActive  string
	UpdatedAt string
	CreatedAt string
}

var UserColumns = buildUserColumns("users")

type userColumns struct {
	tableAlias string
	ID         psql.Expression
	FirstName  psql.Expression
	LastName   psql.Expression
	Username   psql.Expression
	Password   psql.Expression
	Email      psql.Expression
	IsActive   psql.Expression
	UpdatedAt  psql.Expression
	CreatedAt  psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		FirstName:  psql.Quote(alias, "first_name"),
		LastName:   psql.Quote(alias, "last_name"),
		Username:   psql.Quote(alias, "username"),
		Password:   psql.Quote(alias, "password"),
		Email:      psql.Quote(alias, "email"),
		IsActive:   psql.Quote(alias, "is_active"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
		CreatedAt:  psql.Quote(alias, "created_at"),
	}
}

type userWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	FirstName psql.WhereNullMod[Q, string]
	LastName  psql.WhereNullMod[Q, string]
	Username  psql.WhereMod[Q, string]
	Password  psql.WhereMod[Q, string]
	Email     psql.WhereMod[Q, string]
	IsActive  psql.WhereMod[Q, bool]
	UpdatedAt psql.WhereMod[Q, time.Time]
	CreatedAt psql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		FirstName: psql.WhereNull[Q, string](cols.FirstName),
		LastName:  psql.WhereNull[Q, string](cols.LastName),
		Username:  psql.Where[Q, string](cols.Username),
		Password:  psql.Where[Q, string](cols.Password),
		Email:     psql.Where[Q, string](cols.Email),
		IsActive:  psql.Where[Q, bool](cols.IsActive),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

var UserErrors = &userErrors{
	ErrUniqueUsersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"id"},
		s:       "users_pkey",
	},
}

type userErrors struct {
	ErrUniqueUsersPkey *UniqueConstraintError
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID        *uuid.UUID        `db:"id,pk" json:"id"`
	FirstName *sql.Null[string] `db:"first_name" json:"first_name"`
	LastName  *sql.Null[string] `db:"last_name" json:"last_name"`
	Username  *string           `db:"username" json:"username"`
	Password  *string           `db:"password" json:"password"`
	Email     *string           `db:"email" json:"email"`
	IsActive  *bool             `db:"is_active" json:"is_active"`
	UpdatedAt *time.Time        `db:"updated_at" json:"updated_at"`
	CreatedAt *time.Time        `db:"created_at" json:"created_at"`
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID != nil {
		vals = append(vals, "id")
	}

	if s.FirstName != nil {
		vals = append(vals, "first_name")
	}

	if s.LastName != nil {
		vals = append(vals, "last_name")
	}

	if s.Username != nil {
		vals = append(vals, "username")
	}

	if s.Password != nil {
		vals = append(vals, "password")
	}

	if s.Email != nil {
		vals = append(vals, "email")
	}

	if s.IsActive != nil {
		vals = append(vals, "is_active")
	}

	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}

	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}

	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID != nil {
		t.ID = *s.ID
	}
	if s.FirstName != nil {
		t.FirstName = *s.FirstName
	}
	if s.LastName != nil {
		t.LastName = *s.LastName
	}
	if s.Username != nil {
		t.Username = *s.Username
	}
	if s.Password != nil {
		t.Password = *s.Password
	}
	if s.Email != nil {
		t.Email = *s.Email
	}
	if s.IsActive != nil {
		t.IsActive = *s.IsActive
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = *s.UpdatedAt
	}
	if s.CreatedAt != nil {
		t.CreatedAt = *s.CreatedAt
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID != nil {
			vals[0] = psql.Arg(*s.ID)
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.FirstName != nil {
			vals[1] = psql.Arg(*s.FirstName)
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.LastName != nil {
			vals[2] = psql.Arg(*s.LastName)
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Username != nil {
			vals[3] = psql.Arg(*s.Username)
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Password != nil {
			vals[4] = psql.Arg(*s.Password)
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Email != nil {
			vals[5] = psql.Arg(*s.Email)
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.IsActive != nil {
			vals[6] = psql.Arg(*s.IsActive)
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[7] = psql.Arg(*s.UpdatedAt)
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[8] = psql.Arg(*s.CreatedAt)
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.FirstName != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "first_name")...),
			psql.Arg(s.FirstName),
		}})
	}

	if s.LastName != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_name")...),
			psql.Arg(s.LastName),
		}})
	}

	if s.Username != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "username")...),
			psql.Arg(s.Username),
		}})
	}

	if s.Password != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password")...),
			psql.Arg(s.Password),
		}})
	}

	if s.Email != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.IsActive != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			SelectWhere.Users.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Users.Query(
		SelectWhere.Users.ID.EQ(IDPK),
		sm.Columns(Users.Columns().Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Users.Query(
		SelectWhere.Users.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		SelectWhere.Users.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ               string
	CreatedByChapters modAs[Q, chapterColumns]
	CreatedByStories  modAs[Q, storyColumns]
	UserCodes         modAs[Q, userCodeColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		CreatedByChapters: modAs[Q, chapterColumns]{
			c: ChapterColumns,
			f: func(to chapterColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Chapters.Name().As(to.Alias())).On(
						to.CreatedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CreatedByStories: modAs[Q, storyColumns]{
			c: StoryColumns,
			f: func(to storyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Stories.Name().As(to.Alias())).On(
						to.CreatedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UserCodes: modAs[Q, userCodeColumns]{
			c: UserCodeColumns,
			f: func(to userCodeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserCodes.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}

// CreatedByChapters starts a query for related objects on chapters
func (o *User) CreatedByChapters(mods ...bob.Mod[*dialect.SelectQuery]) ChaptersQuery {
	return Chapters.Query(append(mods,
		sm.Where(ChapterColumns.CreatedBy.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) CreatedByChapters(mods ...bob.Mod[*dialect.SelectQuery]) ChaptersQuery {
	pkID := make(pgtypes.Array[uuid.UUID], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Chapters.Query(append(mods,
		sm.Where(psql.Group(ChapterColumns.CreatedBy).OP("IN", PKArgExpr)),
	)...)
}

// CreatedByStories starts a query for related objects on stories
func (o *User) CreatedByStories(mods ...bob.Mod[*dialect.SelectQuery]) StoriesQuery {
	return Stories.Query(append(mods,
		sm.Where(StoryColumns.CreatedBy.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) CreatedByStories(mods ...bob.Mod[*dialect.SelectQuery]) StoriesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Stories.Query(append(mods,
		sm.Where(psql.Group(StoryColumns.CreatedBy).OP("IN", PKArgExpr)),
	)...)
}

// UserCodes starts a query for related objects on user_codes
func (o *User) UserCodes(mods ...bob.Mod[*dialect.SelectQuery]) UserCodesQuery {
	return UserCodes.Query(append(mods,
		sm.Where(UserCodeColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) UserCodes(mods ...bob.Mod[*dialect.SelectQuery]) UserCodesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return UserCodes.Query(append(mods,
		sm.Where(psql.Group(UserCodeColumns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CreatedByChapters":
		rels, ok := retrieved.(ChapterSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByChapters = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.CreatedByUser = o
			}
		}
		return nil
	case "CreatedByStories":
		rels, ok := retrieved.(StorySlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByStories = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.CreatedByUser = o
			}
		}
		return nil
	case "UserCodes":
		rels, ok := retrieved.(UserCodeSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserCodes = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	CreatedByChapters func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByStories  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserCodes         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type CreatedByChaptersLoadInterface interface {
		LoadCreatedByChapters(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByStoriesLoadInterface interface {
		LoadCreatedByStories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserCodesLoadInterface interface {
		LoadUserCodes(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		CreatedByChapters: thenLoadBuilder[Q](
			"CreatedByChapters",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByChaptersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByChapters(ctx, exec, mods...)
			},
		),
		CreatedByStories: thenLoadBuilder[Q](
			"CreatedByStories",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByStoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByStories(ctx, exec, mods...)
			},
		),
		UserCodes: thenLoadBuilder[Q](
			"UserCodes",
			func(ctx context.Context, exec bob.Executor, retrieved UserCodesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserCodes(ctx, exec, mods...)
			},
		),
	}
}

// LoadCreatedByChapters loads the user's CreatedByChapters into the .R struct
func (o *User) LoadCreatedByChapters(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByChapters = nil

	related, err := o.CreatedByChapters(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.CreatedByUser = o
	}

	o.R.CreatedByChapters = related
	return nil
}

// LoadCreatedByChapters loads the user's CreatedByChapters into the .R struct
func (os UserSlice) LoadCreatedByChapters(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	chapters, err := os.CreatedByChapters(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.CreatedByChapters = nil
	}

	for _, o := range os {
		for _, rel := range chapters {
			if o.ID != rel.CreatedBy.V {
				continue
			}

			rel.R.CreatedByUser = o

			o.R.CreatedByChapters = append(o.R.CreatedByChapters, rel)
		}
	}

	return nil
}

// LoadCreatedByStories loads the user's CreatedByStories into the .R struct
func (o *User) LoadCreatedByStories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByStories = nil

	related, err := o.CreatedByStories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.CreatedByUser = o
	}

	o.R.CreatedByStories = related
	return nil
}

// LoadCreatedByStories loads the user's CreatedByStories into the .R struct
func (os UserSlice) LoadCreatedByStories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	stories, err := os.CreatedByStories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.CreatedByStories = nil
	}

	for _, o := range os {
		for _, rel := range stories {
			if o.ID != rel.CreatedBy.V {
				continue
			}

			rel.R.CreatedByUser = o

			o.R.CreatedByStories = append(o.R.CreatedByStories, rel)
		}
	}

	return nil
}

// LoadUserCodes loads the user's UserCodes into the .R struct
func (o *User) LoadUserCodes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserCodes = nil

	related, err := o.UserCodes(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.UserCodes = related
	return nil
}

// LoadUserCodes loads the user's UserCodes into the .R struct
func (os UserSlice) LoadUserCodes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userCodes, err := os.UserCodes(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.UserCodes = nil
	}

	for _, o := range os {
		for _, rel := range userCodes {
			if o.ID != rel.UserID {
				continue
			}

			rel.R.User = o

			o.R.UserCodes = append(o.R.UserCodes, rel)
		}
	}

	return nil
}

func insertUserCreatedByChapters0(ctx context.Context, exec bob.Executor, chapters1 []*ChapterSetter, user0 *User) (ChapterSlice, error) {
	for i := range chapters1 {
		chapters1[i].CreatedBy = func() *sql.Null[uuid.UUID] {
			v := sql.Null[uuid.UUID]{V: user0.ID, Valid: true}
			return &v
		}()
	}

	ret, err := Chapters.Insert(bob.ToMods(chapters1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserCreatedByChapters0: %w", err)
	}

	return ret, nil
}

func attachUserCreatedByChapters0(ctx context.Context, exec bob.Executor, count int, chapters1 ChapterSlice, user0 *User) (ChapterSlice, error) {
	setter := &ChapterSetter{
		CreatedBy: func() *sql.Null[uuid.UUID] {
			v := sql.Null[uuid.UUID]{V: user0.ID, Valid: true}
			return &v
		}(),
	}

	err := chapters1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCreatedByChapters0: %w", err)
	}

	return chapters1, nil
}

func (user0 *User) InsertCreatedByChapters(ctx context.Context, exec bob.Executor, related ...*ChapterSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	chapters1, err := insertUserCreatedByChapters0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.CreatedByChapters = append(user0.R.CreatedByChapters, chapters1...)

	for _, rel := range chapters1 {
		rel.R.CreatedByUser = user0
	}
	return nil
}

func (user0 *User) AttachCreatedByChapters(ctx context.Context, exec bob.Executor, related ...*Chapter) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	chapters1 := ChapterSlice(related)

	_, err = attachUserCreatedByChapters0(ctx, exec, len(related), chapters1, user0)
	if err != nil {
		return err
	}

	user0.R.CreatedByChapters = append(user0.R.CreatedByChapters, chapters1...)

	for _, rel := range related {
		rel.R.CreatedByUser = user0
	}

	return nil
}

func insertUserCreatedByStories0(ctx context.Context, exec bob.Executor, stories1 []*StorySetter, user0 *User) (StorySlice, error) {
	for i := range stories1 {
		stories1[i].CreatedBy = func() *sql.Null[uuid.UUID] {
			v := sql.Null[uuid.UUID]{V: user0.ID, Valid: true}
			return &v
		}()
	}

	ret, err := Stories.Insert(bob.ToMods(stories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserCreatedByStories0: %w", err)
	}

	return ret, nil
}

func attachUserCreatedByStories0(ctx context.Context, exec bob.Executor, count int, stories1 StorySlice, user0 *User) (StorySlice, error) {
	setter := &StorySetter{
		CreatedBy: func() *sql.Null[uuid.UUID] {
			v := sql.Null[uuid.UUID]{V: user0.ID, Valid: true}
			return &v
		}(),
	}

	err := stories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCreatedByStories0: %w", err)
	}

	return stories1, nil
}

func (user0 *User) InsertCreatedByStories(ctx context.Context, exec bob.Executor, related ...*StorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	stories1, err := insertUserCreatedByStories0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.CreatedByStories = append(user0.R.CreatedByStories, stories1...)

	for _, rel := range stories1 {
		rel.R.CreatedByUser = user0
	}
	return nil
}

func (user0 *User) AttachCreatedByStories(ctx context.Context, exec bob.Executor, related ...*Story) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	stories1 := StorySlice(related)

	_, err = attachUserCreatedByStories0(ctx, exec, len(related), stories1, user0)
	if err != nil {
		return err
	}

	user0.R.CreatedByStories = append(user0.R.CreatedByStories, stories1...)

	for _, rel := range related {
		rel.R.CreatedByUser = user0
	}

	return nil
}

func insertUserUserCodes0(ctx context.Context, exec bob.Executor, userCodes1 []*UserCodeSetter, user0 *User) (UserCodeSlice, error) {
	for i := range userCodes1 {
		userCodes1[i].UserID = &user0.ID
	}

	ret, err := UserCodes.Insert(bob.ToMods(userCodes1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserUserCodes0: %w", err)
	}

	return ret, nil
}

func attachUserUserCodes0(ctx context.Context, exec bob.Executor, count int, userCodes1 UserCodeSlice, user0 *User) (UserCodeSlice, error) {
	setter := &UserCodeSetter{
		UserID: &user0.ID,
	}

	err := userCodes1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserCodes0: %w", err)
	}

	return userCodes1, nil
}

func (user0 *User) InsertUserCodes(ctx context.Context, exec bob.Executor, related ...*UserCodeSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	userCodes1, err := insertUserUserCodes0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UserCodes = append(user0.R.UserCodes, userCodes1...)

	for _, rel := range userCodes1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachUserCodes(ctx context.Context, exec bob.Executor, related ...*UserCode) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userCodes1 := UserCodeSlice(related)

	_, err = attachUserUserCodes0(ctx, exec, len(related), userCodes1, user0)
	if err != nil {
		return err
	}

	user0.R.UserCodes = append(user0.R.UserCodes, userCodes1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}
