// Code generated by BobGen psql v0.25.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// UserCode is an object representing the database table.
type UserCode struct {
	ID          uuid.UUID `db:"id,pk" json:"id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Value       string    `db:"value" json:"value"`
	Status      string    `db:"status" json:"status"`
	Type        string    `db:"type" json:"type"`
	ExpiredTime time.Time `db:"expired_time" json:"expired_time"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`

	R userCodeR `db:"-" json:"-"`
}

// UserCodeSlice is an alias for a slice of pointers to UserCode.
// This should almost always be used instead of []*UserCode.
type UserCodeSlice []*UserCode

// UserCodes contains methods to work with the user_codes table
var UserCodes = psql.NewTablex[*UserCode, UserCodeSlice, *UserCodeSetter]("", "user_codes")

// UserCodesQuery is a query on the user_codes table
type UserCodesQuery = *psql.ViewQuery[*UserCode, UserCodeSlice]

// UserCodesStmt is a prepared statment on user_codes
type UserCodesStmt = bob.QueryStmt[*UserCode, UserCodeSlice]

// userCodeR is where relationships are stored.
type userCodeR struct {
	User *User `json:"User"` // user_codes.fk__user_codes__users
}

// UserCodeSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserCodeSetter struct {
	ID          omit.Val[uuid.UUID] `db:"id,pk"`
	UserID      omit.Val[uuid.UUID] `db:"user_id"`
	Value       omit.Val[string]    `db:"value"`
	Status      omit.Val[string]    `db:"status"`
	Type        omit.Val[string]    `db:"type"`
	ExpiredTime omit.Val[time.Time] `db:"expired_time"`
	UpdatedAt   omit.Val[time.Time] `db:"updated_at"`
	CreatedAt   omit.Val[time.Time] `db:"created_at"`
}

func (s UserCodeSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Value.IsUnset() {
		vals = append(vals, "value")
	}

	if !s.Status.IsUnset() {
		vals = append(vals, "status")
	}

	if !s.Type.IsUnset() {
		vals = append(vals, "type")
	}

	if !s.ExpiredTime.IsUnset() {
		vals = append(vals, "expired_time")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	return vals
}

func (s UserCodeSetter) Overwrite(t *UserCode) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Value.IsUnset() {
		t.Value, _ = s.Value.Get()
	}
	if !s.Status.IsUnset() {
		t.Status, _ = s.Status.Get()
	}
	if !s.Type.IsUnset() {
		t.Type, _ = s.Type.Get()
	}
	if !s.ExpiredTime.IsUnset() {
		t.ExpiredTime, _ = s.ExpiredTime.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
}

func (s UserCodeSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 8)
	if s.ID.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.ID)
	}

	if s.UserID.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.UserID)
	}

	if s.Value.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.Value)
	}

	if s.Status.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.Status)
	}

	if s.Type.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.Type)
	}

	if s.ExpiredTime.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.ExpiredTime)
	}

	if s.UpdatedAt.IsUnset() {
		vals[6] = psql.Raw("DEFAULT")
	} else {
		vals[6] = psql.Arg(s.UpdatedAt)
	}

	if s.CreatedAt.IsUnset() {
		vals[7] = psql.Raw("DEFAULT")
	} else {
		vals[7] = psql.Arg(s.CreatedAt)
	}

	return im.Values(vals...)
}

func (s UserCodeSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s UserCodeSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.Value.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "value")...),
			psql.Arg(s.Value),
		}})
	}

	if !s.Status.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.Type.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if !s.ExpiredTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expired_time")...),
			psql.Arg(s.ExpiredTime),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

type userCodeColumnNames struct {
	ID          string
	UserID      string
	Value       string
	Status      string
	Type        string
	ExpiredTime string
	UpdatedAt   string
	CreatedAt   string
}

type userCodeRelationshipJoins[Q dialect.Joinable] struct {
	User bob.Mod[Q]
}

func buildUserCodeRelationshipJoins[Q dialect.Joinable](ctx context.Context, typ string) userCodeRelationshipJoins[Q] {
	return userCodeRelationshipJoins[Q]{
		User: userCodesJoinUser[Q](ctx, typ),
	}
}

func userCodesJoin[Q dialect.Joinable](ctx context.Context) joinSet[userCodeRelationshipJoins[Q]] {
	return joinSet[userCodeRelationshipJoins[Q]]{
		InnerJoin: buildUserCodeRelationshipJoins[Q](ctx, clause.InnerJoin),
		LeftJoin:  buildUserCodeRelationshipJoins[Q](ctx, clause.LeftJoin),
		RightJoin: buildUserCodeRelationshipJoins[Q](ctx, clause.RightJoin),
	}
}

var UserCodeColumns = struct {
	ID          psql.Expression
	UserID      psql.Expression
	Value       psql.Expression
	Status      psql.Expression
	Type        psql.Expression
	ExpiredTime psql.Expression
	UpdatedAt   psql.Expression
	CreatedAt   psql.Expression
}{
	ID:          psql.Quote("user_codes", "id"),
	UserID:      psql.Quote("user_codes", "user_id"),
	Value:       psql.Quote("user_codes", "value"),
	Status:      psql.Quote("user_codes", "status"),
	Type:        psql.Quote("user_codes", "type"),
	ExpiredTime: psql.Quote("user_codes", "expired_time"),
	UpdatedAt:   psql.Quote("user_codes", "updated_at"),
	CreatedAt:   psql.Quote("user_codes", "created_at"),
}

type userCodeWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	UserID      psql.WhereMod[Q, uuid.UUID]
	Value       psql.WhereMod[Q, string]
	Status      psql.WhereMod[Q, string]
	Type        psql.WhereMod[Q, string]
	ExpiredTime psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
}

func UserCodeWhere[Q psql.Filterable]() userCodeWhere[Q] {
	return userCodeWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](UserCodeColumns.ID),
		UserID:      psql.Where[Q, uuid.UUID](UserCodeColumns.UserID),
		Value:       psql.Where[Q, string](UserCodeColumns.Value),
		Status:      psql.Where[Q, string](UserCodeColumns.Status),
		Type:        psql.Where[Q, string](UserCodeColumns.Type),
		ExpiredTime: psql.Where[Q, time.Time](UserCodeColumns.ExpiredTime),
		UpdatedAt:   psql.Where[Q, time.Time](UserCodeColumns.UpdatedAt),
		CreatedAt:   psql.Where[Q, time.Time](UserCodeColumns.CreatedAt),
	}
}

// FindUserCode retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserCode(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*UserCode, error) {
	if len(cols) == 0 {
		return UserCodes.Query(
			ctx, exec,
			SelectWhere.UserCodes.ID.EQ(IDPK),
		).One()
	}

	return UserCodes.Query(
		ctx, exec,
		SelectWhere.UserCodes.ID.EQ(IDPK),
		sm.Columns(UserCodes.Columns().Only(cols...)),
	).One()
}

// UserCodeExists checks the presence of a single record by primary key
func UserCodeExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return UserCodes.Query(
		ctx, exec,
		SelectWhere.UserCodes.ID.EQ(IDPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the UserCode
func (o *UserCode) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

// Update uses an executor to update the UserCode
func (o *UserCode) Update(ctx context.Context, exec bob.Executor, s *UserCodeSetter) error {
	return UserCodes.Update(ctx, exec, s, o)
}

// Delete deletes a single UserCode record with an executor
func (o *UserCode) Delete(ctx context.Context, exec bob.Executor) error {
	return UserCodes.Delete(ctx, exec, o)
}

// Reload refreshes the UserCode using the executor
func (o *UserCode) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserCodes.Query(
		ctx, exec,
		SelectWhere.UserCodes.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o UserCodeSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserCodeSetter) error {
	return UserCodes.Update(ctx, exec, &vals, o...)
}

func (o UserCodeSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return UserCodes.Delete(ctx, exec, o...)
}

func (o UserCodeSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]uuid.UUID, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.UserCodes.ID.In(IDPK...),
	)

	o2, err := UserCodes.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func userCodesJoinUser[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Users.NameAs(ctx)).On(
			UserColumns.ID.EQ(UserCodeColumns.UserID),
		),
	}
}

// User starts a query for related objects on users
func (o *UserCode) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(ctx, exec, append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserCodeSlice) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.UserID)
	}

	return Users.Query(ctx, exec, append(mods,
		sm.Where(psql.Group(UserColumns.ID).In(PKArgs...)),
	)...)
}

func (o *UserCode) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userCode cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserCodes = UserCodeSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userCode has no relationship %q", name)
	}
}

func PreloadUserCodeUser(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*User, UserSlice](orm.Relationship{
		Name: "User",
		Sides: []orm.RelSide{
			{
				From: "user_codes",
				To:   TableNames.Users,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Users.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.UserCodes.UserID,
				},
				ToColumns: []string{
					ColumnNames.Users.ID,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadUserCodeUser(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserCodeUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserCodeUser", retrieved)
		}

		err := loader.LoadUserCodeUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserCodeUser loads the userCode's User into the .R struct
func (o *UserCode) LoadUserCodeUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.UserCodes = UserCodeSlice{o}

	o.R.User = related
	return nil
}

// LoadUserCodeUser loads the userCode's User into the .R struct
func (os UserCodeSlice) LoadUserCodeUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.UserCodes = append(rel.R.UserCodes, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachUserCodeUser0(ctx context.Context, exec bob.Executor, count int, userCode0 *UserCode, user1 *User) (*UserCode, error) {
	setter := &UserCodeSetter{
		UserID: omit.From(user1.ID),
	}

	err := UserCodes.Update(ctx, exec, setter, userCode0)
	if err != nil {
		return nil, fmt.Errorf("attachUserCodeUser0: %w", err)
	}

	return userCode0, nil
}

func (userCode0 *UserCode) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserCodeUser0(ctx, exec, 1, userCode0, user1)
	if err != nil {
		return err
	}

	userCode0.R.User = user1

	user1.R.UserCodes = append(user1.R.UserCodes, userCode0)

	return nil
}

func (userCode0 *UserCode) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserCodeUser0(ctx, exec, 1, userCode0, user1)
	if err != nil {
		return err
	}

	userCode0.R.User = user1

	user1.R.UserCodes = append(user1.R.UserCodes, userCode0)

	return nil
}
