// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// UserCode is an object representing the database table.
type UserCode struct {
	ID          uuid.UUID `db:"id,pk" json:"id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Value       string    `db:"value" json:"value"`
	Status      string    `db:"status" json:"status"`
	Type        string    `db:"type" json:"type"`
	ExpiredTime time.Time `db:"expired_time" json:"expired_time"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`

	R userCodeR `db:"-" json:"-"`
}

// UserCodeSlice is an alias for a slice of pointers to UserCode.
// This should almost always be used instead of []*UserCode.
type UserCodeSlice []*UserCode

// UserCodes contains methods to work with the user_codes table
var UserCodes = psql.NewTablex[*UserCode, UserCodeSlice, *UserCodeSetter]("", "user_codes")

// UserCodesQuery is a query on the user_codes table
type UserCodesQuery = *psql.ViewQuery[*UserCode, UserCodeSlice]

// userCodeR is where relationships are stored.
type userCodeR struct {
	User *User `json:"User"` // user_codes.fk__user_codes__users
}

type userCodeColumnNames struct {
	ID          string
	UserID      string
	Value       string
	Status      string
	Type        string
	ExpiredTime string
	UpdatedAt   string
	CreatedAt   string
}

var UserCodeColumns = buildUserCodeColumns("user_codes")

type userCodeColumns struct {
	tableAlias  string
	ID          psql.Expression
	UserID      psql.Expression
	Value       psql.Expression
	Status      psql.Expression
	Type        psql.Expression
	ExpiredTime psql.Expression
	UpdatedAt   psql.Expression
	CreatedAt   psql.Expression
}

func (c userCodeColumns) Alias() string {
	return c.tableAlias
}

func (userCodeColumns) AliasedAs(alias string) userCodeColumns {
	return buildUserCodeColumns(alias)
}

func buildUserCodeColumns(alias string) userCodeColumns {
	return userCodeColumns{
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		UserID:      psql.Quote(alias, "user_id"),
		Value:       psql.Quote(alias, "value"),
		Status:      psql.Quote(alias, "status"),
		Type:        psql.Quote(alias, "type"),
		ExpiredTime: psql.Quote(alias, "expired_time"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
		CreatedAt:   psql.Quote(alias, "created_at"),
	}
}

type userCodeWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	UserID      psql.WhereMod[Q, uuid.UUID]
	Value       psql.WhereMod[Q, string]
	Status      psql.WhereMod[Q, string]
	Type        psql.WhereMod[Q, string]
	ExpiredTime psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
}

func (userCodeWhere[Q]) AliasedAs(alias string) userCodeWhere[Q] {
	return buildUserCodeWhere[Q](buildUserCodeColumns(alias))
}

func buildUserCodeWhere[Q psql.Filterable](cols userCodeColumns) userCodeWhere[Q] {
	return userCodeWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		UserID:      psql.Where[Q, uuid.UUID](cols.UserID),
		Value:       psql.Where[Q, string](cols.Value),
		Status:      psql.Where[Q, string](cols.Status),
		Type:        psql.Where[Q, string](cols.Type),
		ExpiredTime: psql.Where[Q, time.Time](cols.ExpiredTime),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

var UserCodeErrors = &userCodeErrors{
	ErrUniqueUserCodesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "user_codes",
		columns: []string{"id"},
		s:       "user_codes_pkey",
	},
}

type userCodeErrors struct {
	ErrUniqueUserCodesPkey *UniqueConstraintError
}

// UserCodeSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserCodeSetter struct {
	ID          *uuid.UUID `db:"id,pk" json:"id"`
	UserID      *uuid.UUID `db:"user_id" json:"user_id"`
	Value       *string    `db:"value" json:"value"`
	Status      *string    `db:"status" json:"status"`
	Type        *string    `db:"type" json:"type"`
	ExpiredTime *time.Time `db:"expired_time" json:"expired_time"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

func (s UserCodeSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID != nil {
		vals = append(vals, "id")
	}

	if s.UserID != nil {
		vals = append(vals, "user_id")
	}

	if s.Value != nil {
		vals = append(vals, "value")
	}

	if s.Status != nil {
		vals = append(vals, "status")
	}

	if s.Type != nil {
		vals = append(vals, "type")
	}

	if s.ExpiredTime != nil {
		vals = append(vals, "expired_time")
	}

	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}

	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}

	return vals
}

func (s UserCodeSetter) Overwrite(t *UserCode) {
	if s.ID != nil {
		t.ID = *s.ID
	}
	if s.UserID != nil {
		t.UserID = *s.UserID
	}
	if s.Value != nil {
		t.Value = *s.Value
	}
	if s.Status != nil {
		t.Status = *s.Status
	}
	if s.Type != nil {
		t.Type = *s.Type
	}
	if s.ExpiredTime != nil {
		t.ExpiredTime = *s.ExpiredTime
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = *s.UpdatedAt
	}
	if s.CreatedAt != nil {
		t.CreatedAt = *s.CreatedAt
	}
}

func (s *UserCodeSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserCodes.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID != nil {
			vals[0] = psql.Arg(*s.ID)
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID != nil {
			vals[1] = psql.Arg(*s.UserID)
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Value != nil {
			vals[2] = psql.Arg(*s.Value)
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Status != nil {
			vals[3] = psql.Arg(*s.Status)
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Type != nil {
			vals[4] = psql.Arg(*s.Type)
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.ExpiredTime != nil {
			vals[5] = psql.Arg(*s.ExpiredTime)
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[6] = psql.Arg(*s.UpdatedAt)
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[7] = psql.Arg(*s.CreatedAt)
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserCodeSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserCodeSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Value != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "value")...),
			psql.Arg(s.Value),
		}})
	}

	if s.Status != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.Type != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.ExpiredTime != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expired_time")...),
			psql.Arg(s.ExpiredTime),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindUserCode retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserCode(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*UserCode, error) {
	if len(cols) == 0 {
		return UserCodes.Query(
			SelectWhere.UserCodes.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return UserCodes.Query(
		SelectWhere.UserCodes.ID.EQ(IDPK),
		sm.Columns(UserCodes.Columns().Only(cols...)),
	).One(ctx, exec)
}

// UserCodeExists checks the presence of a single record by primary key
func UserCodeExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return UserCodes.Query(
		SelectWhere.UserCodes.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserCode is retrieved from the database
func (o *UserCode) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserCodes.AfterSelectHooks.RunHooks(ctx, exec, UserCodeSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserCodes.AfterInsertHooks.RunHooks(ctx, exec, UserCodeSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserCodes.AfterUpdateHooks.RunHooks(ctx, exec, UserCodeSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserCodes.AfterDeleteHooks.RunHooks(ctx, exec, UserCodeSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UserCode
func (o *UserCode) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *UserCode) pkEQ() dialect.Expression {
	return psql.Quote("user_codes", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserCode
func (o *UserCode) Update(ctx context.Context, exec bob.Executor, s *UserCodeSetter) error {
	v, err := UserCodes.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserCode record with an executor
func (o *UserCode) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserCodes.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserCode using the executor
func (o *UserCode) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserCodes.Query(
		SelectWhere.UserCodes.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserCodeSlice is retrieved from the database
func (o UserCodeSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserCodes.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserCodes.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserCodes.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserCodes.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserCodeSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("user_codes", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserCodeSlice) copyMatchingRows(from ...*UserCode) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserCodeSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserCodes.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserCode:
				o.copyMatchingRows(retrieved)
			case []*UserCode:
				o.copyMatchingRows(retrieved...)
			case UserCodeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserCode or a slice of UserCode
				// then run the AfterUpdateHooks on the slice
				_, err = UserCodes.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserCodeSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserCodes.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserCode:
				o.copyMatchingRows(retrieved)
			case []*UserCode:
				o.copyMatchingRows(retrieved...)
			case UserCodeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserCode or a slice of UserCode
				// then run the AfterDeleteHooks on the slice
				_, err = UserCodes.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserCodeSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserCodeSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserCodes.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserCodeSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserCodes.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserCodeSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserCodes.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type userCodeJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j userCodeJoins[Q]) aliasedAs(alias string) userCodeJoins[Q] {
	return buildUserCodeJoins[Q](buildUserCodeColumns(alias), j.typ)
}

func buildUserCodeJoins[Q dialect.Joinable](cols userCodeColumns, typ string) userCodeJoins[Q] {
	return userCodeJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}

// User starts a query for related objects on users
func (o *UserCode) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserCodeSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], len(os))
	for i, o := range os {
		pkUserID[i] = o.UserID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *UserCode) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userCode cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserCodes = UserCodeSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userCode has no relationship %q", name)
	}
}

type userCodePreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildUserCodePreloader() userCodePreloader {
	return userCodePreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](orm.Relationship{
				Name: "User",
				Sides: []orm.RelSide{
					{
						From: TableNames.UserCodes,
						To:   TableNames.Users,
						FromColumns: []string{
							ColumnNames.UserCodes.UserID,
						},
						ToColumns: []string{
							ColumnNames.Users.ID,
						},
					},
				},
			}, Users.Columns().Names(), opts...)
		},
	}
}

type userCodeThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserCodeThenLoader[Q orm.Loadable]() userCodeThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userCodeThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the userCode's User into the .R struct
func (o *UserCode) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UserCodes = UserCodeSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the userCode's User into the .R struct
func (os UserCodeSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.UserCodes = append(rel.R.UserCodes, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachUserCodeUser0(ctx context.Context, exec bob.Executor, count int, userCode0 *UserCode, user1 *User) (*UserCode, error) {
	setter := &UserCodeSetter{
		UserID: &user1.ID,
	}

	err := userCode0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCodeUser0: %w", err)
	}

	return userCode0, nil
}

func (userCode0 *UserCode) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserCodeUser0(ctx, exec, 1, userCode0, user1)
	if err != nil {
		return err
	}

	userCode0.R.User = user1

	user1.R.UserCodes = append(user1.R.UserCodes, userCode0)

	return nil
}

func (userCode0 *UserCode) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserCodeUser0(ctx, exec, 1, userCode0, user1)
	if err != nil {
		return err
	}

	userCode0.R.User = user1

	user1.R.UserCodes = append(user1.R.UserCodes, userCode0)

	return nil
}
